<?php

/*
 * F1-02. Fonte declarativa da classificacao do catalogo PostgreSQL de
 * 2026-08-26, mais as cinco tabelas raiz de F1-01. Cada nome e enumerado:
 * adicoes/remocoes no banco falham no comando de verificacao.
 *
 * A classificacao descreve o destino de seguranca desejado. Ela nao ativa
 * ainda tenant_id/RLS: isso e feito, com migracao e testes, em F1-03 a F1-10.
 */
$entries = [];
$register = static function (array $tables, string $class, string $owner, string $justification) use (&$entries): void {
    foreach ($tables as $table) {
        $entries[$table] = compact('class', 'owner', 'justification');
    }
};

$register([
    'cache',
    'cache_locks',
    'cidades_plataforma',
    'estados',
    'failed_jobs',
    'ibpt_aliquotas',
    'job_batches',
    'jobs',
    'logradouros_oficiais',
    'migrations',
    'municipios_ibge',
    'otp_consumidos',
    'password_policies',
    'password_reset_tokens',
    'permission_conditions',
    'permission_role',
    'permissions',
    'personal_access_tokens',
    'plano_conta_modelos',
    'platform_admins',
    'platform_audit_logs',
    'produtoorigens',
    'role_user',
    'role_versions',
    'roles',
    'sessions',
    'unidades',
    'user_2fa',
    'users',
], 'PLATFORM', 'Platform Operations', 'Referencia, identidade, autorizacao ou infraestrutura compartilhada; nao contem dado operacional de empresa.');

$register([
    'assinatura_eventos',
    'assinaturas',
    'break_glass_grants',
    'limite_overrides',
    'plano_limites',
    'plano_recurso',
    'planos',
    'planos_conta',
    'recurso_overrides',
    'tenant_accounts',
    'tenant_memberships',
    'tenant_companies',
    'tenant_company_grants',
    'tenant_legacy_group_scopes',
    'tenant_network_links',
], 'TENANT', 'SaaS Tenant Boundary', 'Contrato, conta SaaS ou vinculacao entre tenants; acesso dependera do envelope e das policies canonicas.');

$register([
    'entregador_posicoes_ultima',
    'estoquefechamentos',
    'geo_pares_ignorados',
    'monitora_malha_cache',
    'monitora_ultima_posicao',
    'monitora_viagens_cache',
    'monitora_vias_cache',
    'rotas_cache',
    'venda_ativa_clientes',
], 'DERIVED', 'Domain Data Lifecycle', 'Projecao/cache reconstruivel; deve ter origem catalogada, TTL ou mecanismo de recomposicao antes do cutover.');

$register([
    '_bkp_autocadastro_20260820',
    'importacoes_cnefe',
    'importacoes_logradouro',
    'migracao_descartes',
    'migracoes',
    'tenant_staging_artifacts',
], 'STAGING', 'Data Migration Operations', 'Entrada ou descarte operacional temporario; exige owner, TTL e policy de staging em F1-09.');

$register([
    'alcada_descontos',
    'alertas',
    'app_devices',
    'audit_logs',
    'boleto_historicos',
    'boleto_ocorrencias',
    'boletos',
    'cargos',
    'cartao_transacoes',
    'cartas_correcao',
    'centros_custo',
    'checklist_execucoes',
    'checklist_perguntas',
    'checklist_respostas',
    'checklists',
    'cheques',
    'cliente_enderecos',
    'cliente_papeis',
    'cliente_identidades',
    'cliente_revisoes',
    'cliente_vinculos',
    'clientecontatosituacoes',
    'clientecontatotipos',
    'clientedependentes',
    'clienteinteracoes',
    'clienteprecos',
    'clientes',
    'clientetelefones',
    'colaborador_comissoes',
    'colaborador_exames',
    'colaborador_familias',
    'colaborador_pontos',
    'colaborador_recessos',
    'colaborador_turnos',
    'colaboradores',
    'comissao_excecoes',
    'comodato_avaliacoes',
    'comodato_config',
    'comodato_contratos',
    'comodato_movimentos',
    'comodatos',
    'conciliacao_lancamentos',
    'condicaopagamento_parcelas',
    'condicaopagamentos',
    'config_fiscais',
    'config_globais',
    'conta_extrato_regras',
    'conta_transferencias',
    'contafechamentos',
    'contamovimento_estornos',
    'contamovimentos',
    'contamovimentotipos',
    'contas',
    'convenio_fechamento_pedidos',
    'convenio_fechamentos',
    'convenios',
    'cupom_fiscal_itens',
    'cupons_fiscais',
    'departamentos',
    'documentos',
    'empresa_bens',
    'empresa_cidade',
    'empresa_configs',
    'empresa_user',
    'empresas',
    'entregador_bloqueios',
    'estoque_acertos',
    'estoque_inventario_itens',
    'estoque_inventarios',
    'estoque_requisicoes',
    'estoque_transferencia_itens',
    'estoque_transferencias',
    'estoquehistorico',
    'estoquesaldos',
    'financeiroparcelas',
    'financeirorateios',
    'financeiros',
    'gasdopovo_beneficios',
    'grupos',
    'inutilizacoes_fiscais',
    'jornadas',
    'login_logs',
    'logistica_configs',
    'malha_fiscal',
    'mcmms',
    'meta_vendas',
    'missao_atribuicoes',
    'missao_evidencias',
    'missao_trilha',
    'missao_visitas',
    'missoes',
    'monitora_cerca_pontos',
    'monitora_cercas',
    'monitora_posicoes',
    'monitora_rotas',
    'monitora_veiculo_tipos',
    'monitora_veiculos',
    'motivos_nao_venda',
    'nf_imposto_estados',
    'nf_impostos',
    'nf_recebida_itens',
    'nf_recebidas',
    'nota_itens',
    'nota_volumes',
    'notas_fiscais',
    'pagamentos_online',
    'pedido_atribuicoes',
    'pedido_avaliacoes',
    'pedido_comprovacoes',
    'pedido_motivos_atraso',
    'pedido_ocorrencias',
    'pedido_solicitacoes',
    'pedidoitens',
    'pedidooperacoes',
    'pedidos',
    'pedidosituacaohistorico',
    'pedidosituacoes',
    'pix_cobrancas',
    'pos_vendas',
    'produto_condicao_precos',
    'produto_operacao_fiscal',
    'produtos',
    'promocoes',
    'promotor_visitas',
    'remessas_cnab',
    'requisicoes_idempotentes',
    'security_events',
    'sequencias',
    'setores',
    'setores_org',
    'sorteio_numeros',
    'sorteios',
    'taxas_entrega',
    'telefonia_chamadas',
    'telefonia_ligacoes',
    'transportadoras',
    'vale_gas',
    'vale_gas_vendas',
    'veiculo_abastecimentos',
    'veiculo_documentos',
    'veiculo_entradas_saidas',
    'veiculo_pneus',
    'veiculo_tipos',
    'veiculo_trocas_oleo',
    'veiculos',
    'venda_ativas',
], 'COMPANY', 'Business Domain Owners', 'Registro operacional do dominio que deve receber empresa_id e tenant_id conforme F1-03, sem usar grupo_id como fronteira de acesso.');

/*
 * Reclassificacao de 2026-08-29. Estas 19 estavam como PLATFORM sob a
 * justificativa "nao contem dado operacional de empresa". Os dados e o codigo
 * diziam o contrario:
 *
 *  - todas tem `grupo_id`, unicidade `(grupo_id, descricao)` e model com
 *    `BelongsToGrupo`;
 *  - todas sao EDITAVEIS pela revenda (CadastroApoioRegistry / controllers
 *    proprios de cidade e logradouro) — inclusive `bancos` e `estados_civis`;
 *  - na copia real o seed ja duplicou `tipos_documento_veiculo` 7 + 7 entre os
 *    dois grupos, provando que na pratica sao copias por tenant.
 *
 * Se a revenda edita, o dado e dela: uma renomeando um banco ou desativando uma
 * unidade de medida nao pode afetar a concorrente. O PLATFORM de verdade e o
 * cadastro publico e imutavel, sem `grupo_id` — `municipios_ibge` e
 * `logradouros_oficiais`, que seguem PLATFORM e nao tem tela de edicao.
 */
$register([
    'agencias',
    'bairros',
    'bancos',
    'cidades',
    'estados_civis',
    'feriados',
    'operacoes_fiscais',
    'parentescos',
    'produtoclasses',
    'profissoes',
    'regioes',
    'ruas',
    'segmentos',
    'telefonetipos',
    'tipo_combustiveis',
    'tipopessoas',
    'tipos_documento_veiculo',
    'tipos_exame',
    'unidadesmedida',
], 'COMPANY', 'Business Domain Owners', 'Cadastro escopado por grupo e editavel pela revenda: a policy canonica de configuracao substitui a policy legada por app.grupo_id. Catalogo publico e imutavel permanece PLATFORM (municipios_ibge, logradouros_oficiais).');

return $entries;
