<?php

use Illuminate\Database\Seeder;

class CidadesTableSPSeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades de São Paulo
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 3500105, 'uf' => 'SP', 'descricao' => 'Adamantina']);
		DB::table('cidades')->insert(['id' => 3500204, 'uf' => 'SP', 'descricao' => 'Adolfo']);
		DB::table('cidades')->insert(['id' => 3500303, 'uf' => 'SP', 'descricao' => 'Aguaí']);
		DB::table('cidades')->insert(['id' => 3500402, 'uf' => 'SP', 'descricao' => 'Águas da Prata']);
		DB::table('cidades')->insert(['id' => 3500501, 'uf' => 'SP', 'descricao' => 'Águas de Lindóia']);
		DB::table('cidades')->insert(['id' => 3500550, 'uf' => 'SP', 'descricao' => 'Águas de Santa Bárbara']);
		DB::table('cidades')->insert(['id' => 3500600, 'uf' => 'SP', 'descricao' => 'Águas de São Pedro']);
		DB::table('cidades')->insert(['id' => 3500709, 'uf' => 'SP', 'descricao' => 'Agudos']);
		DB::table('cidades')->insert(['id' => 3500758, 'uf' => 'SP', 'descricao' => 'Alambari']);
		DB::table('cidades')->insert(['id' => 3500808, 'uf' => 'SP', 'descricao' => 'Alfredo Marcondes']);
		DB::table('cidades')->insert(['id' => 3500907, 'uf' => 'SP', 'descricao' => 'Altair']);
		DB::table('cidades')->insert(['id' => 3501004, 'uf' => 'SP', 'descricao' => 'Altinópolis']);
		DB::table('cidades')->insert(['id' => 3501103, 'uf' => 'SP', 'descricao' => 'Alto Alegre']);
		DB::table('cidades')->insert(['id' => 3501152, 'uf' => 'SP', 'descricao' => 'Alumínio']);
		DB::table('cidades')->insert(['id' => 3501202, 'uf' => 'SP', 'descricao' => 'Álvares Florence']);
		DB::table('cidades')->insert(['id' => 3501301, 'uf' => 'SP', 'descricao' => 'Álvares Machado']);
		DB::table('cidades')->insert(['id' => 3501400, 'uf' => 'SP', 'descricao' => 'Álvaro de Carvalho']);
		DB::table('cidades')->insert(['id' => 3501509, 'uf' => 'SP', 'descricao' => 'Alvinlândia']);
		DB::table('cidades')->insert(['id' => 3501608, 'uf' => 'SP', 'descricao' => 'Americana']);
		DB::table('cidades')->insert(['id' => 3501707, 'uf' => 'SP', 'descricao' => 'Américo Brasiliense']);
		DB::table('cidades')->insert(['id' => 3501806, 'uf' => 'SP', 'descricao' => 'Américo de Campos']);
		DB::table('cidades')->insert(['id' => 3501905, 'uf' => 'SP', 'descricao' => 'Amparo']);
		DB::table('cidades')->insert(['id' => 3502002, 'uf' => 'SP', 'descricao' => 'Analândia']);
		DB::table('cidades')->insert(['id' => 3502101, 'uf' => 'SP', 'descricao' => 'Andradina']);
		DB::table('cidades')->insert(['id' => 3502200, 'uf' => 'SP', 'descricao' => 'Angatuba']);
		DB::table('cidades')->insert(['id' => 3502309, 'uf' => 'SP', 'descricao' => 'Anhembi']);
		DB::table('cidades')->insert(['id' => 3502408, 'uf' => 'SP', 'descricao' => 'Anhumas']);
		DB::table('cidades')->insert(['id' => 3502507, 'uf' => 'SP', 'descricao' => 'Aparecida']);
		DB::table('cidades')->insert(['id' => 3502606, 'uf' => 'SP', 'descricao' => 'Aparecida d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3502705, 'uf' => 'SP', 'descricao' => 'Apiaí']);
		DB::table('cidades')->insert(['id' => 3502754, 'uf' => 'SP', 'descricao' => 'Araçariguama']);
		DB::table('cidades')->insert(['id' => 3502804, 'uf' => 'SP', 'descricao' => 'Araçatuba']);
		DB::table('cidades')->insert(['id' => 3502903, 'uf' => 'SP', 'descricao' => 'Araçoiaba da Serra']);
		DB::table('cidades')->insert(['id' => 3503000, 'uf' => 'SP', 'descricao' => 'Aramina']);
		DB::table('cidades')->insert(['id' => 3503109, 'uf' => 'SP', 'descricao' => 'Arandu']);
		DB::table('cidades')->insert(['id' => 3503158, 'uf' => 'SP', 'descricao' => 'Arapeí']);
		DB::table('cidades')->insert(['id' => 3503208, 'uf' => 'SP', 'descricao' => 'Araraquara']);
		DB::table('cidades')->insert(['id' => 3503307, 'uf' => 'SP', 'descricao' => 'Araras']);
		DB::table('cidades')->insert(['id' => 3503356, 'uf' => 'SP', 'descricao' => 'Arco-Íris']);
		DB::table('cidades')->insert(['id' => 3503406, 'uf' => 'SP', 'descricao' => 'Arealva']);
		DB::table('cidades')->insert(['id' => 3503505, 'uf' => 'SP', 'descricao' => 'Areias']);
		DB::table('cidades')->insert(['id' => 3503604, 'uf' => 'SP', 'descricao' => 'Areiópolis']);
		DB::table('cidades')->insert(['id' => 3503703, 'uf' => 'SP', 'descricao' => 'Ariranha']);
		DB::table('cidades')->insert(['id' => 3503802, 'uf' => 'SP', 'descricao' => 'Artur Nogueira']);
		DB::table('cidades')->insert(['id' => 3503901, 'uf' => 'SP', 'descricao' => 'Arujá']);
		DB::table('cidades')->insert(['id' => 3503950, 'uf' => 'SP', 'descricao' => 'Aspásia']);
		DB::table('cidades')->insert(['id' => 3504008, 'uf' => 'SP', 'descricao' => 'Assis']);
		DB::table('cidades')->insert(['id' => 3504107, 'uf' => 'SP', 'descricao' => 'Atibaia']);
		DB::table('cidades')->insert(['id' => 3504206, 'uf' => 'SP', 'descricao' => 'Auriflama']);
		DB::table('cidades')->insert(['id' => 3504305, 'uf' => 'SP', 'descricao' => 'Avaí']);
		DB::table('cidades')->insert(['id' => 3504404, 'uf' => 'SP', 'descricao' => 'Avanhandava']);
		DB::table('cidades')->insert(['id' => 3504503, 'uf' => 'SP', 'descricao' => 'Avaré']);
		DB::table('cidades')->insert(['id' => 3504602, 'uf' => 'SP', 'descricao' => 'Bady Bassitt']);
		DB::table('cidades')->insert(['id' => 3504701, 'uf' => 'SP', 'descricao' => 'Balbinos']);
		DB::table('cidades')->insert(['id' => 3504800, 'uf' => 'SP', 'descricao' => 'Bálsamo']);
		DB::table('cidades')->insert(['id' => 3504909, 'uf' => 'SP', 'descricao' => 'Bananal']);
		DB::table('cidades')->insert(['id' => 3505005, 'uf' => 'SP', 'descricao' => 'Barão de Antonina']);
		DB::table('cidades')->insert(['id' => 3505104, 'uf' => 'SP', 'descricao' => 'Barbosa']);
		DB::table('cidades')->insert(['id' => 3505203, 'uf' => 'SP', 'descricao' => 'Bariri']);
		DB::table('cidades')->insert(['id' => 3505302, 'uf' => 'SP', 'descricao' => 'Barra Bonita']);
		DB::table('cidades')->insert(['id' => 3505351, 'uf' => 'SP', 'descricao' => 'Barra do Chapéu']);
		DB::table('cidades')->insert(['id' => 3505401, 'uf' => 'SP', 'descricao' => 'Barra do Turvo']);
		DB::table('cidades')->insert(['id' => 3505500, 'uf' => 'SP', 'descricao' => 'Barretos']);
		DB::table('cidades')->insert(['id' => 3505609, 'uf' => 'SP', 'descricao' => 'Barrinha']);
		DB::table('cidades')->insert(['id' => 3505708, 'uf' => 'SP', 'descricao' => 'Barueri']);
		DB::table('cidades')->insert(['id' => 3505807, 'uf' => 'SP', 'descricao' => 'Bastos']);
		DB::table('cidades')->insert(['id' => 3505906, 'uf' => 'SP', 'descricao' => 'Batatais']);
		DB::table('cidades')->insert(['id' => 3506003, 'uf' => 'SP', 'descricao' => 'Bauru']);
		DB::table('cidades')->insert(['id' => 3506102, 'uf' => 'SP', 'descricao' => 'Bebedouro']);
		DB::table('cidades')->insert(['id' => 3506201, 'uf' => 'SP', 'descricao' => 'Bento de Abreu']);
		DB::table('cidades')->insert(['id' => 3506300, 'uf' => 'SP', 'descricao' => 'Bernardino de Campos']);
		DB::table('cidades')->insert(['id' => 3506359, 'uf' => 'SP', 'descricao' => 'Bertioga']);
		DB::table('cidades')->insert(['id' => 3506409, 'uf' => 'SP', 'descricao' => 'Bilac']);
		DB::table('cidades')->insert(['id' => 3506508, 'uf' => 'SP', 'descricao' => 'Birigui']);
		DB::table('cidades')->insert(['id' => 3506607, 'uf' => 'SP', 'descricao' => 'Biritiba-Mirim']);
		DB::table('cidades')->insert(['id' => 3506706, 'uf' => 'SP', 'descricao' => 'Boa Esperança do Sul']);
		DB::table('cidades')->insert(['id' => 3506805, 'uf' => 'SP', 'descricao' => 'Bocaina']);
		DB::table('cidades')->insert(['id' => 3506904, 'uf' => 'SP', 'descricao' => 'Bofete']);
		DB::table('cidades')->insert(['id' => 3507001, 'uf' => 'SP', 'descricao' => 'Boituva']);
		DB::table('cidades')->insert(['id' => 3507100, 'uf' => 'SP', 'descricao' => 'Bom Jesus dos Perdões']);
		DB::table('cidades')->insert(['id' => 3507159, 'uf' => 'SP', 'descricao' => 'Bom Sucesso de Itararé']);
		DB::table('cidades')->insert(['id' => 3507209, 'uf' => 'SP', 'descricao' => 'Borá']);
		DB::table('cidades')->insert(['id' => 3507308, 'uf' => 'SP', 'descricao' => 'Boracéia']);
		DB::table('cidades')->insert(['id' => 3507407, 'uf' => 'SP', 'descricao' => 'Borborema']);
		DB::table('cidades')->insert(['id' => 3507456, 'uf' => 'SP', 'descricao' => 'Borebi']);
		DB::table('cidades')->insert(['id' => 3507506, 'uf' => 'SP', 'descricao' => 'Botucatu']);
		DB::table('cidades')->insert(['id' => 3507605, 'uf' => 'SP', 'descricao' => 'Bragança Paulista']);
		DB::table('cidades')->insert(['id' => 3507704, 'uf' => 'SP', 'descricao' => 'Braúna']);
		DB::table('cidades')->insert(['id' => 3507753, 'uf' => 'SP', 'descricao' => 'Brejo Alegre']);
		DB::table('cidades')->insert(['id' => 3507803, 'uf' => 'SP', 'descricao' => 'Brodowski']);
		DB::table('cidades')->insert(['id' => 3507902, 'uf' => 'SP', 'descricao' => 'Brotas']);
		DB::table('cidades')->insert(['id' => 3508009, 'uf' => 'SP', 'descricao' => 'Buri']);
		DB::table('cidades')->insert(['id' => 3508108, 'uf' => 'SP', 'descricao' => 'Buritama']);
		DB::table('cidades')->insert(['id' => 3508207, 'uf' => 'SP', 'descricao' => 'Buritizal']);
		DB::table('cidades')->insert(['id' => 3508306, 'uf' => 'SP', 'descricao' => 'Cabrália Paulista']);
		DB::table('cidades')->insert(['id' => 3508405, 'uf' => 'SP', 'descricao' => 'Cabreúva']);
		DB::table('cidades')->insert(['id' => 3508504, 'uf' => 'SP', 'descricao' => 'Caçapava']);
		DB::table('cidades')->insert(['id' => 3508603, 'uf' => 'SP', 'descricao' => 'Cachoeira Paulista']);
		DB::table('cidades')->insert(['id' => 3508702, 'uf' => 'SP', 'descricao' => 'Caconde']);
		DB::table('cidades')->insert(['id' => 3508801, 'uf' => 'SP', 'descricao' => 'Cafelândia']);
		DB::table('cidades')->insert(['id' => 3508900, 'uf' => 'SP', 'descricao' => 'Caiabu']);
		DB::table('cidades')->insert(['id' => 3509007, 'uf' => 'SP', 'descricao' => 'Caieiras']);
		DB::table('cidades')->insert(['id' => 3509106, 'uf' => 'SP', 'descricao' => 'Caiuá']);
		DB::table('cidades')->insert(['id' => 3509205, 'uf' => 'SP', 'descricao' => 'Cajamar']);
		DB::table('cidades')->insert(['id' => 3509254, 'uf' => 'SP', 'descricao' => 'Cajati']);
		DB::table('cidades')->insert(['id' => 3509304, 'uf' => 'SP', 'descricao' => 'Cajobi']);
		DB::table('cidades')->insert(['id' => 3509403, 'uf' => 'SP', 'descricao' => 'Cajuru']);
		DB::table('cidades')->insert(['id' => 3509452, 'uf' => 'SP', 'descricao' => 'Campina do Monte Alegre']);
		DB::table('cidades')->insert(['id' => 3509502, 'uf' => 'SP', 'descricao' => 'Campinas']);
		DB::table('cidades')->insert(['id' => 3509601, 'uf' => 'SP', 'descricao' => 'Campo Limpo Paulista']);
		DB::table('cidades')->insert(['id' => 3509700, 'uf' => 'SP', 'descricao' => 'Campos do Jordão']);
		DB::table('cidades')->insert(['id' => 3509809, 'uf' => 'SP', 'descricao' => 'Campos Novos Paulista']);
		DB::table('cidades')->insert(['id' => 3509908, 'uf' => 'SP', 'descricao' => 'Cananéia']);
		DB::table('cidades')->insert(['id' => 3509957, 'uf' => 'SP', 'descricao' => 'Canas']);
		DB::table('cidades')->insert(['id' => 3510005, 'uf' => 'SP', 'descricao' => 'Cândido Mota']);
		DB::table('cidades')->insert(['id' => 3510104, 'uf' => 'SP', 'descricao' => 'Cândido Rodrigues']);
		DB::table('cidades')->insert(['id' => 3510153, 'uf' => 'SP', 'descricao' => 'Canitar']);
		DB::table('cidades')->insert(['id' => 3510203, 'uf' => 'SP', 'descricao' => 'Capão Bonito']);
		DB::table('cidades')->insert(['id' => 3510302, 'uf' => 'SP', 'descricao' => 'Capela do Alto']);
		DB::table('cidades')->insert(['id' => 3510401, 'uf' => 'SP', 'descricao' => 'Capivari']);
		DB::table('cidades')->insert(['id' => 3510500, 'uf' => 'SP', 'descricao' => 'Caraguatatuba']);
		DB::table('cidades')->insert(['id' => 3510609, 'uf' => 'SP', 'descricao' => 'Carapicuíba']);
		DB::table('cidades')->insert(['id' => 3510708, 'uf' => 'SP', 'descricao' => 'Cardoso']);
		DB::table('cidades')->insert(['id' => 3510807, 'uf' => 'SP', 'descricao' => 'Casa Branca']);
		DB::table('cidades')->insert(['id' => 3510906, 'uf' => 'SP', 'descricao' => 'Cássia dos Coqueiros']);
		DB::table('cidades')->insert(['id' => 3511003, 'uf' => 'SP', 'descricao' => 'Castilho']);
		DB::table('cidades')->insert(['id' => 3511102, 'uf' => 'SP', 'descricao' => 'Catanduva']);
		DB::table('cidades')->insert(['id' => 3511201, 'uf' => 'SP', 'descricao' => 'Catiguá']);
		DB::table('cidades')->insert(['id' => 3511300, 'uf' => 'SP', 'descricao' => 'Cedral']);
		DB::table('cidades')->insert(['id' => 3511409, 'uf' => 'SP', 'descricao' => 'Cerqueira César']);
		DB::table('cidades')->insert(['id' => 3511508, 'uf' => 'SP', 'descricao' => 'Cerquilho']);
		DB::table('cidades')->insert(['id' => 3511607, 'uf' => 'SP', 'descricao' => 'Cesário Lange']);
		DB::table('cidades')->insert(['id' => 3511706, 'uf' => 'SP', 'descricao' => 'Charqueada']);
		DB::table('cidades')->insert(['id' => 3511904, 'uf' => 'SP', 'descricao' => 'Clementina']);
		DB::table('cidades')->insert(['id' => 3512001, 'uf' => 'SP', 'descricao' => 'Colina']);
		DB::table('cidades')->insert(['id' => 3512100, 'uf' => 'SP', 'descricao' => 'Colômbia']);
		DB::table('cidades')->insert(['id' => 3512209, 'uf' => 'SP', 'descricao' => 'Conchal']);
		DB::table('cidades')->insert(['id' => 3512308, 'uf' => 'SP', 'descricao' => 'Conchas']);
		DB::table('cidades')->insert(['id' => 3512407, 'uf' => 'SP', 'descricao' => 'Cordeirópolis']);
		DB::table('cidades')->insert(['id' => 3512506, 'uf' => 'SP', 'descricao' => 'Coroados']);
		DB::table('cidades')->insert(['id' => 3512605, 'uf' => 'SP', 'descricao' => 'Coronel Macedo']);
		DB::table('cidades')->insert(['id' => 3512704, 'uf' => 'SP', 'descricao' => 'Corumbataí']);
		DB::table('cidades')->insert(['id' => 3512803, 'uf' => 'SP', 'descricao' => 'Cosmópolis']);
		DB::table('cidades')->insert(['id' => 3512902, 'uf' => 'SP', 'descricao' => 'Cosmorama']);
		DB::table('cidades')->insert(['id' => 3513009, 'uf' => 'SP', 'descricao' => 'Cotia']);
		DB::table('cidades')->insert(['id' => 3513108, 'uf' => 'SP', 'descricao' => 'Cravinhos']);
		DB::table('cidades')->insert(['id' => 3513207, 'uf' => 'SP', 'descricao' => 'Cristais Paulista']);
		DB::table('cidades')->insert(['id' => 3513306, 'uf' => 'SP', 'descricao' => 'Cruzália']);
		DB::table('cidades')->insert(['id' => 3513405, 'uf' => 'SP', 'descricao' => 'Cruzeiro']);
		DB::table('cidades')->insert(['id' => 3513504, 'uf' => 'SP', 'descricao' => 'Cubatão']);
		DB::table('cidades')->insert(['id' => 3513603, 'uf' => 'SP', 'descricao' => 'Cunha']);
		DB::table('cidades')->insert(['id' => 3513702, 'uf' => 'SP', 'descricao' => 'Descalvado']);
		DB::table('cidades')->insert(['id' => 3513801, 'uf' => 'SP', 'descricao' => 'Diadema']);
		DB::table('cidades')->insert(['id' => 3513850, 'uf' => 'SP', 'descricao' => 'Dirce Reis']);
		DB::table('cidades')->insert(['id' => 3513900, 'uf' => 'SP', 'descricao' => 'Divinolândia']);
		DB::table('cidades')->insert(['id' => 3514007, 'uf' => 'SP', 'descricao' => 'Dobrada']);
		DB::table('cidades')->insert(['id' => 3514106, 'uf' => 'SP', 'descricao' => 'Dois Córregos']);
		DB::table('cidades')->insert(['id' => 3514205, 'uf' => 'SP', 'descricao' => 'Dolcinópolis']);
		DB::table('cidades')->insert(['id' => 3514304, 'uf' => 'SP', 'descricao' => 'Dourado']);
		DB::table('cidades')->insert(['id' => 3514403, 'uf' => 'SP', 'descricao' => 'Dracena']);
		DB::table('cidades')->insert(['id' => 3514502, 'uf' => 'SP', 'descricao' => 'Duartina']);
		DB::table('cidades')->insert(['id' => 3514601, 'uf' => 'SP', 'descricao' => 'Dumont']);
		DB::table('cidades')->insert(['id' => 3514700, 'uf' => 'SP', 'descricao' => 'Echaporã']);
		DB::table('cidades')->insert(['id' => 3514809, 'uf' => 'SP', 'descricao' => 'Eldorado']);
		DB::table('cidades')->insert(['id' => 3514908, 'uf' => 'SP', 'descricao' => 'Elias Fausto']);
		DB::table('cidades')->insert(['id' => 3514924, 'uf' => 'SP', 'descricao' => 'Elisiário']);
		DB::table('cidades')->insert(['id' => 3514957, 'uf' => 'SP', 'descricao' => 'Embaúba']);
		DB::table('cidades')->insert(['id' => 3515004, 'uf' => 'SP', 'descricao' => 'Embu']);
		DB::table('cidades')->insert(['id' => 3515103, 'uf' => 'SP', 'descricao' => 'Embu-Guaçu']);
		DB::table('cidades')->insert(['id' => 3515129, 'uf' => 'SP', 'descricao' => 'Emilianópolis']);
		DB::table('cidades')->insert(['id' => 3515152, 'uf' => 'SP', 'descricao' => 'Engenheiro Coelho']);
		DB::table('cidades')->insert(['id' => 3515186, 'uf' => 'SP', 'descricao' => 'Espírito Santo do Pinhal']);
		DB::table('cidades')->insert(['id' => 3515194, 'uf' => 'SP', 'descricao' => 'Espírito Santo do Turvo']);
		DB::table('cidades')->insert(['id' => 3515202, 'uf' => 'SP', 'descricao' => 'Estrela d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3515301, 'uf' => 'SP', 'descricao' => 'Estrela do Norte']);
		DB::table('cidades')->insert(['id' => 3515350, 'uf' => 'SP', 'descricao' => 'Euclides da Cunha Paulista']);
		DB::table('cidades')->insert(['id' => 3515400, 'uf' => 'SP', 'descricao' => 'Fartura']);
		DB::table('cidades')->insert(['id' => 3515509, 'uf' => 'SP', 'descricao' => 'Fernandópolis']);
		DB::table('cidades')->insert(['id' => 3515608, 'uf' => 'SP', 'descricao' => 'Fernando Prestes']);
		DB::table('cidades')->insert(['id' => 3515657, 'uf' => 'SP', 'descricao' => 'Fernão']);
		DB::table('cidades')->insert(['id' => 3515707, 'uf' => 'SP', 'descricao' => 'Ferraz de Vasconcelos']);
		DB::table('cidades')->insert(['id' => 3515806, 'uf' => 'SP', 'descricao' => 'Flora Rica']);
		DB::table('cidades')->insert(['id' => 3515905, 'uf' => 'SP', 'descricao' => 'Floreal']);
		DB::table('cidades')->insert(['id' => 3516002, 'uf' => 'SP', 'descricao' => 'Flórida Paulista']);
		DB::table('cidades')->insert(['id' => 3516101, 'uf' => 'SP', 'descricao' => 'Florínia']);
		DB::table('cidades')->insert(['id' => 3516200, 'uf' => 'SP', 'descricao' => 'Franca']);
		DB::table('cidades')->insert(['id' => 3516309, 'uf' => 'SP', 'descricao' => 'Francisco Morato']);
		DB::table('cidades')->insert(['id' => 3516408, 'uf' => 'SP', 'descricao' => 'Franco da Rocha']);
		DB::table('cidades')->insert(['id' => 3516507, 'uf' => 'SP', 'descricao' => 'Gabriel Monteiro']);
		DB::table('cidades')->insert(['id' => 3516606, 'uf' => 'SP', 'descricao' => 'Gália']);
		DB::table('cidades')->insert(['id' => 3516705, 'uf' => 'SP', 'descricao' => 'Garça']);
		DB::table('cidades')->insert(['id' => 3516804, 'uf' => 'SP', 'descricao' => 'Gastão Vidigal']);
		DB::table('cidades')->insert(['id' => 3516853, 'uf' => 'SP', 'descricao' => 'Gavião Peixoto']);
		DB::table('cidades')->insert(['id' => 3516903, 'uf' => 'SP', 'descricao' => 'General Salgado']);
		DB::table('cidades')->insert(['id' => 3517000, 'uf' => 'SP', 'descricao' => 'Getulina']);
		DB::table('cidades')->insert(['id' => 3517109, 'uf' => 'SP', 'descricao' => 'Glicério']);
		DB::table('cidades')->insert(['id' => 3517208, 'uf' => 'SP', 'descricao' => 'Guaiçara']);
		DB::table('cidades')->insert(['id' => 3517307, 'uf' => 'SP', 'descricao' => 'Guaimbê']);
		DB::table('cidades')->insert(['id' => 3517406, 'uf' => 'SP', 'descricao' => 'Guaíra']);
		DB::table('cidades')->insert(['id' => 3517505, 'uf' => 'SP', 'descricao' => 'Guapiaçu']);
		DB::table('cidades')->insert(['id' => 3517604, 'uf' => 'SP', 'descricao' => 'Guapiara']);
		DB::table('cidades')->insert(['id' => 3517703, 'uf' => 'SP', 'descricao' => 'Guará']);
		DB::table('cidades')->insert(['id' => 3517802, 'uf' => 'SP', 'descricao' => 'Guaraçaí']);
		DB::table('cidades')->insert(['id' => 3517901, 'uf' => 'SP', 'descricao' => 'Guaraci']);
		DB::table('cidades')->insert(['id' => 3518008, 'uf' => 'SP', 'descricao' => 'Guarani d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3518107, 'uf' => 'SP', 'descricao' => 'Guarantã']);
		DB::table('cidades')->insert(['id' => 3518206, 'uf' => 'SP', 'descricao' => 'Guararapes']);
		DB::table('cidades')->insert(['id' => 3518305, 'uf' => 'SP', 'descricao' => 'Guararema']);
		DB::table('cidades')->insert(['id' => 3518404, 'uf' => 'SP', 'descricao' => 'Guaratinguetá']);
		DB::table('cidades')->insert(['id' => 3518503, 'uf' => 'SP', 'descricao' => 'Guareí']);
		DB::table('cidades')->insert(['id' => 3518602, 'uf' => 'SP', 'descricao' => 'Guariba']);
		DB::table('cidades')->insert(['id' => 3518701, 'uf' => 'SP', 'descricao' => 'Guarujá']);
		DB::table('cidades')->insert(['id' => 3518800, 'uf' => 'SP', 'descricao' => 'Guarulhos']);
		DB::table('cidades')->insert(['id' => 3518859, 'uf' => 'SP', 'descricao' => 'Guatapará']);
		DB::table('cidades')->insert(['id' => 3518909, 'uf' => 'SP', 'descricao' => 'Guzolândia']);
		DB::table('cidades')->insert(['id' => 3519006, 'uf' => 'SP', 'descricao' => 'Herculândia']);
		DB::table('cidades')->insert(['id' => 3519055, 'uf' => 'SP', 'descricao' => 'Holambra']);
		DB::table('cidades')->insert(['id' => 3519071, 'uf' => 'SP', 'descricao' => 'Hortolândia']);
		DB::table('cidades')->insert(['id' => 3519105, 'uf' => 'SP', 'descricao' => 'Iacanga']);
		DB::table('cidades')->insert(['id' => 3519204, 'uf' => 'SP', 'descricao' => 'Iacri']);
		DB::table('cidades')->insert(['id' => 3519253, 'uf' => 'SP', 'descricao' => 'Iaras']);
		DB::table('cidades')->insert(['id' => 3519303, 'uf' => 'SP', 'descricao' => 'Ibaté']);
		DB::table('cidades')->insert(['id' => 3519402, 'uf' => 'SP', 'descricao' => 'Ibirá']);
		DB::table('cidades')->insert(['id' => 3519501, 'uf' => 'SP', 'descricao' => 'Ibirarema']);
		DB::table('cidades')->insert(['id' => 3519600, 'uf' => 'SP', 'descricao' => 'Ibitinga']);
		DB::table('cidades')->insert(['id' => 3519709, 'uf' => 'SP', 'descricao' => 'Ibiúna']);
		DB::table('cidades')->insert(['id' => 3519808, 'uf' => 'SP', 'descricao' => 'Icém']);
		DB::table('cidades')->insert(['id' => 3519907, 'uf' => 'SP', 'descricao' => 'Iepê']);
		DB::table('cidades')->insert(['id' => 3520004, 'uf' => 'SP', 'descricao' => 'Igaraçu do Tietê']);
		DB::table('cidades')->insert(['id' => 3520103, 'uf' => 'SP', 'descricao' => 'Igarapava']);
		DB::table('cidades')->insert(['id' => 3520202, 'uf' => 'SP', 'descricao' => 'Igaratá']);
		DB::table('cidades')->insert(['id' => 3520301, 'uf' => 'SP', 'descricao' => 'Iguape']);
		DB::table('cidades')->insert(['id' => 3520400, 'uf' => 'SP', 'descricao' => 'Ilhabela']);
		DB::table('cidades')->insert(['id' => 3520426, 'uf' => 'SP', 'descricao' => 'Ilha Comprida']);
		DB::table('cidades')->insert(['id' => 3520442, 'uf' => 'SP', 'descricao' => 'Ilha Solteira']);
		DB::table('cidades')->insert(['id' => 3520509, 'uf' => 'SP', 'descricao' => 'Indaiatuba']);
		DB::table('cidades')->insert(['id' => 3520608, 'uf' => 'SP', 'descricao' => 'Indiana']);
		DB::table('cidades')->insert(['id' => 3520707, 'uf' => 'SP', 'descricao' => 'Indiaporã']);
		DB::table('cidades')->insert(['id' => 3520806, 'uf' => 'SP', 'descricao' => 'Inúbia Paulista']);
		DB::table('cidades')->insert(['id' => 3520905, 'uf' => 'SP', 'descricao' => 'Ipaussu']);
		DB::table('cidades')->insert(['id' => 3521002, 'uf' => 'SP', 'descricao' => 'Iperó']);
		DB::table('cidades')->insert(['id' => 3521101, 'uf' => 'SP', 'descricao' => 'Ipeúna']);
		DB::table('cidades')->insert(['id' => 3521150, 'uf' => 'SP', 'descricao' => 'Ipiguá']);
		DB::table('cidades')->insert(['id' => 3521200, 'uf' => 'SP', 'descricao' => 'Iporanga']);
		DB::table('cidades')->insert(['id' => 3521309, 'uf' => 'SP', 'descricao' => 'Ipuã']);
		DB::table('cidades')->insert(['id' => 3521408, 'uf' => 'SP', 'descricao' => 'Iracemápolis']);
		DB::table('cidades')->insert(['id' => 3521507, 'uf' => 'SP', 'descricao' => 'Irapuã']);
		DB::table('cidades')->insert(['id' => 3521606, 'uf' => 'SP', 'descricao' => 'Irapuru']);
		DB::table('cidades')->insert(['id' => 3521705, 'uf' => 'SP', 'descricao' => 'Itaberá']);
		DB::table('cidades')->insert(['id' => 3521804, 'uf' => 'SP', 'descricao' => 'Itaí']);
		DB::table('cidades')->insert(['id' => 3521903, 'uf' => 'SP', 'descricao' => 'Itajobi']);
		DB::table('cidades')->insert(['id' => 3522000, 'uf' => 'SP', 'descricao' => 'Itaju']);
		DB::table('cidades')->insert(['id' => 3522109, 'uf' => 'SP', 'descricao' => 'Itanhaém']);
		DB::table('cidades')->insert(['id' => 3522158, 'uf' => 'SP', 'descricao' => 'Itaóca']);
		DB::table('cidades')->insert(['id' => 3522208, 'uf' => 'SP', 'descricao' => 'Itapecerica da Serra']);
		DB::table('cidades')->insert(['id' => 3522307, 'uf' => 'SP', 'descricao' => 'Itapetininga']);
		DB::table('cidades')->insert(['id' => 3522406, 'uf' => 'SP', 'descricao' => 'Itapeva']);
		DB::table('cidades')->insert(['id' => 3522505, 'uf' => 'SP', 'descricao' => 'Itapevi']);
		DB::table('cidades')->insert(['id' => 3522604, 'uf' => 'SP', 'descricao' => 'Itapira']);
		DB::table('cidades')->insert(['id' => 3522653, 'uf' => 'SP', 'descricao' => 'Itapirapuã Paulista']);
		DB::table('cidades')->insert(['id' => 3522703, 'uf' => 'SP', 'descricao' => 'Itápolis']);
		DB::table('cidades')->insert(['id' => 3522802, 'uf' => 'SP', 'descricao' => 'Itaporanga']);
		DB::table('cidades')->insert(['id' => 3522901, 'uf' => 'SP', 'descricao' => 'Itapuí']);
		DB::table('cidades')->insert(['id' => 3523008, 'uf' => 'SP', 'descricao' => 'Itapura']);
		DB::table('cidades')->insert(['id' => 3523107, 'uf' => 'SP', 'descricao' => 'Itaquaquecetuba']);
		DB::table('cidades')->insert(['id' => 3523206, 'uf' => 'SP', 'descricao' => 'Itararé']);
		DB::table('cidades')->insert(['id' => 3523305, 'uf' => 'SP', 'descricao' => 'Itariri']);
		DB::table('cidades')->insert(['id' => 3523404, 'uf' => 'SP', 'descricao' => 'Itatiba']);
		DB::table('cidades')->insert(['id' => 3523503, 'uf' => 'SP', 'descricao' => 'Itatinga']);
		DB::table('cidades')->insert(['id' => 3523602, 'uf' => 'SP', 'descricao' => 'Itirapina']);
		DB::table('cidades')->insert(['id' => 3523701, 'uf' => 'SP', 'descricao' => 'Itirapuã']);
		DB::table('cidades')->insert(['id' => 3523800, 'uf' => 'SP', 'descricao' => 'Itobi']);
		DB::table('cidades')->insert(['id' => 3523909, 'uf' => 'SP', 'descricao' => 'Itu']);
		DB::table('cidades')->insert(['id' => 3524006, 'uf' => 'SP', 'descricao' => 'Itupeva']);
		DB::table('cidades')->insert(['id' => 3524105, 'uf' => 'SP', 'descricao' => 'Ituverava']);
		DB::table('cidades')->insert(['id' => 3524204, 'uf' => 'SP', 'descricao' => 'Jaborandi']);
		DB::table('cidades')->insert(['id' => 3524303, 'uf' => 'SP', 'descricao' => 'Jaboticabal']);
		DB::table('cidades')->insert(['id' => 3524402, 'uf' => 'SP', 'descricao' => 'Jacareí']);
		DB::table('cidades')->insert(['id' => 3524501, 'uf' => 'SP', 'descricao' => 'Jaci']);
		DB::table('cidades')->insert(['id' => 3524600, 'uf' => 'SP', 'descricao' => 'Jacupiranga']);
		DB::table('cidades')->insert(['id' => 3524709, 'uf' => 'SP', 'descricao' => 'Jaguariúna']);
		DB::table('cidades')->insert(['id' => 3524808, 'uf' => 'SP', 'descricao' => 'Jales']);
		DB::table('cidades')->insert(['id' => 3524907, 'uf' => 'SP', 'descricao' => 'Jambeiro']);
		DB::table('cidades')->insert(['id' => 3525003, 'uf' => 'SP', 'descricao' => 'Jandira']);
		DB::table('cidades')->insert(['id' => 3525102, 'uf' => 'SP', 'descricao' => 'Jardinópolis']);
		DB::table('cidades')->insert(['id' => 3525201, 'uf' => 'SP', 'descricao' => 'Jarinu']);
		DB::table('cidades')->insert(['id' => 3525300, 'uf' => 'SP', 'descricao' => 'Jaú']);
		DB::table('cidades')->insert(['id' => 3525409, 'uf' => 'SP', 'descricao' => 'Jeriquara']);
		DB::table('cidades')->insert(['id' => 3525508, 'uf' => 'SP', 'descricao' => 'Joanópolis']);
		DB::table('cidades')->insert(['id' => 3525607, 'uf' => 'SP', 'descricao' => 'João Ramalho']);
		DB::table('cidades')->insert(['id' => 3525706, 'uf' => 'SP', 'descricao' => 'José Bonifácio']);
		DB::table('cidades')->insert(['id' => 3525805, 'uf' => 'SP', 'descricao' => 'Júlio Mesquita']);
		DB::table('cidades')->insert(['id' => 3525854, 'uf' => 'SP', 'descricao' => 'Jumirim']);
		DB::table('cidades')->insert(['id' => 3525904, 'uf' => 'SP', 'descricao' => 'Jundiaí']);
		DB::table('cidades')->insert(['id' => 3526001, 'uf' => 'SP', 'descricao' => 'Junqueirópolis']);
		DB::table('cidades')->insert(['id' => 3526100, 'uf' => 'SP', 'descricao' => 'Juquiá']);
		DB::table('cidades')->insert(['id' => 3526209, 'uf' => 'SP', 'descricao' => 'Juquitiba']);
		DB::table('cidades')->insert(['id' => 3526308, 'uf' => 'SP', 'descricao' => 'Lagoinha']);
		DB::table('cidades')->insert(['id' => 3526407, 'uf' => 'SP', 'descricao' => 'Laranjal Paulista']);
		DB::table('cidades')->insert(['id' => 3526506, 'uf' => 'SP', 'descricao' => 'Lavínia']);
		DB::table('cidades')->insert(['id' => 3526605, 'uf' => 'SP', 'descricao' => 'Lavrinhas']);
		DB::table('cidades')->insert(['id' => 3526704, 'uf' => 'SP', 'descricao' => 'Leme']);
		DB::table('cidades')->insert(['id' => 3526803, 'uf' => 'SP', 'descricao' => 'Lençóis Paulista']);
		DB::table('cidades')->insert(['id' => 3526902, 'uf' => 'SP', 'descricao' => 'Limeira']);
		DB::table('cidades')->insert(['id' => 3527009, 'uf' => 'SP', 'descricao' => 'Lindóia']);
		DB::table('cidades')->insert(['id' => 3527108, 'uf' => 'SP', 'descricao' => 'Lins']);
		DB::table('cidades')->insert(['id' => 3527207, 'uf' => 'SP', 'descricao' => 'Lorena']);
		DB::table('cidades')->insert(['id' => 3527256, 'uf' => 'SP', 'descricao' => 'Lourdes']);
		DB::table('cidades')->insert(['id' => 3527306, 'uf' => 'SP', 'descricao' => 'Louveira']);
		DB::table('cidades')->insert(['id' => 3527405, 'uf' => 'SP', 'descricao' => 'Lucélia']);
		DB::table('cidades')->insert(['id' => 3527504, 'uf' => 'SP', 'descricao' => 'Lucianópolis']);
		DB::table('cidades')->insert(['id' => 3527603, 'uf' => 'SP', 'descricao' => 'Luís Antônio']);
		DB::table('cidades')->insert(['id' => 3527702, 'uf' => 'SP', 'descricao' => 'Luiziânia']);
		DB::table('cidades')->insert(['id' => 3527801, 'uf' => 'SP', 'descricao' => 'Lupércio']);
		DB::table('cidades')->insert(['id' => 3527900, 'uf' => 'SP', 'descricao' => 'Lutécia']);
		DB::table('cidades')->insert(['id' => 3528007, 'uf' => 'SP', 'descricao' => 'Macatuba']);
		DB::table('cidades')->insert(['id' => 3528106, 'uf' => 'SP', 'descricao' => 'Macaubal']);
		DB::table('cidades')->insert(['id' => 3528205, 'uf' => 'SP', 'descricao' => 'Macedônia']);
		DB::table('cidades')->insert(['id' => 3528304, 'uf' => 'SP', 'descricao' => 'Magda']);
		DB::table('cidades')->insert(['id' => 3528403, 'uf' => 'SP', 'descricao' => 'Mairinque']);
		DB::table('cidades')->insert(['id' => 3528502, 'uf' => 'SP', 'descricao' => 'Mairiporã']);
		DB::table('cidades')->insert(['id' => 3528601, 'uf' => 'SP', 'descricao' => 'Manduri']);
		DB::table('cidades')->insert(['id' => 3528700, 'uf' => 'SP', 'descricao' => 'Marabá Paulista']);
		DB::table('cidades')->insert(['id' => 3528809, 'uf' => 'SP', 'descricao' => 'Maracaí']);
		DB::table('cidades')->insert(['id' => 3528858, 'uf' => 'SP', 'descricao' => 'Marapoama']);
		DB::table('cidades')->insert(['id' => 3528908, 'uf' => 'SP', 'descricao' => 'Mariápolis']);
		DB::table('cidades')->insert(['id' => 3529005, 'uf' => 'SP', 'descricao' => 'Marília']);
		DB::table('cidades')->insert(['id' => 3529104, 'uf' => 'SP', 'descricao' => 'Marinópolis']);
		DB::table('cidades')->insert(['id' => 3529203, 'uf' => 'SP', 'descricao' => 'Martinópolis']);
		DB::table('cidades')->insert(['id' => 3529302, 'uf' => 'SP', 'descricao' => 'Matão']);
		DB::table('cidades')->insert(['id' => 3529401, 'uf' => 'SP', 'descricao' => 'Mauá']);
		DB::table('cidades')->insert(['id' => 3529500, 'uf' => 'SP', 'descricao' => 'Mendonça']);
		DB::table('cidades')->insert(['id' => 3529609, 'uf' => 'SP', 'descricao' => 'Meridiano']);
		DB::table('cidades')->insert(['id' => 3529658, 'uf' => 'SP', 'descricao' => 'Mesópolis']);
		DB::table('cidades')->insert(['id' => 3529708, 'uf' => 'SP', 'descricao' => 'Miguelópolis']);
		DB::table('cidades')->insert(['id' => 3529807, 'uf' => 'SP', 'descricao' => 'Mineiros do Tietê']);
		DB::table('cidades')->insert(['id' => 3529906, 'uf' => 'SP', 'descricao' => 'Miracatu']);
		DB::table('cidades')->insert(['id' => 3530003, 'uf' => 'SP', 'descricao' => 'Mira Estrela']);
		DB::table('cidades')->insert(['id' => 3530102, 'uf' => 'SP', 'descricao' => 'Mirandópolis']);
		DB::table('cidades')->insert(['id' => 3530201, 'uf' => 'SP', 'descricao' => 'Mirante do Paranapanema']);
		DB::table('cidades')->insert(['id' => 3530300, 'uf' => 'SP', 'descricao' => 'Mirassol']);
		DB::table('cidades')->insert(['id' => 3530409, 'uf' => 'SP', 'descricao' => 'Mirassolândia']);
		DB::table('cidades')->insert(['id' => 3530508, 'uf' => 'SP', 'descricao' => 'Mococa']);
		DB::table('cidades')->insert(['id' => 3530607, 'uf' => 'SP', 'descricao' => 'Mogi das Cruzes']);
		DB::table('cidades')->insert(['id' => 3530706, 'uf' => 'SP', 'descricao' => 'Mogi Guaçu']);
		DB::table('cidades')->insert(['id' => 3530805, 'uf' => 'SP', 'descricao' => 'Moji Mirim']);
		DB::table('cidades')->insert(['id' => 3530904, 'uf' => 'SP', 'descricao' => 'Mombuca']);
		DB::table('cidades')->insert(['id' => 3531001, 'uf' => 'SP', 'descricao' => 'Monções']);
		DB::table('cidades')->insert(['id' => 3531100, 'uf' => 'SP', 'descricao' => 'Mongaguá']);
		DB::table('cidades')->insert(['id' => 3531209, 'uf' => 'SP', 'descricao' => 'Monte Alegre do Sul']);
		DB::table('cidades')->insert(['id' => 3531308, 'uf' => 'SP', 'descricao' => 'Monte Alto']);
		DB::table('cidades')->insert(['id' => 3531407, 'uf' => 'SP', 'descricao' => 'Monte Aprazível']);
		DB::table('cidades')->insert(['id' => 3531506, 'uf' => 'SP', 'descricao' => 'Monte Azul Paulista']);
		DB::table('cidades')->insert(['id' => 3531605, 'uf' => 'SP', 'descricao' => 'Monte Castelo']);
		DB::table('cidades')->insert(['id' => 3531704, 'uf' => 'SP', 'descricao' => 'Monteiro Lobato']);
		DB::table('cidades')->insert(['id' => 3531803, 'uf' => 'SP', 'descricao' => 'Monte Mor']);
		DB::table('cidades')->insert(['id' => 3531902, 'uf' => 'SP', 'descricao' => 'Morro Agudo']);
		DB::table('cidades')->insert(['id' => 3532009, 'uf' => 'SP', 'descricao' => 'Morungaba']);
		DB::table('cidades')->insert(['id' => 3532058, 'uf' => 'SP', 'descricao' => 'Motuca']);
		DB::table('cidades')->insert(['id' => 3532108, 'uf' => 'SP', 'descricao' => 'Murutinga do Sul']);
		DB::table('cidades')->insert(['id' => 3532157, 'uf' => 'SP', 'descricao' => 'Nantes']);
		DB::table('cidades')->insert(['id' => 3532207, 'uf' => 'SP', 'descricao' => 'Narandiba']);
		DB::table('cidades')->insert(['id' => 3532306, 'uf' => 'SP', 'descricao' => 'Natividade da Serra']);
		DB::table('cidades')->insert(['id' => 3532405, 'uf' => 'SP', 'descricao' => 'Nazaré Paulista']);
		DB::table('cidades')->insert(['id' => 3532504, 'uf' => 'SP', 'descricao' => 'Neves Paulista']);
		DB::table('cidades')->insert(['id' => 3532603, 'uf' => 'SP', 'descricao' => 'Nhandeara']);
		DB::table('cidades')->insert(['id' => 3532702, 'uf' => 'SP', 'descricao' => 'Nipoã']);
		DB::table('cidades')->insert(['id' => 3532801, 'uf' => 'SP', 'descricao' => 'Nova Aliança']);
		DB::table('cidades')->insert(['id' => 3532827, 'uf' => 'SP', 'descricao' => 'Nova Campina']);
		DB::table('cidades')->insert(['id' => 3532843, 'uf' => 'SP', 'descricao' => 'Nova Canaã Paulista']);
		DB::table('cidades')->insert(['id' => 3532868, 'uf' => 'SP', 'descricao' => 'Nova Castilho']);
		DB::table('cidades')->insert(['id' => 3532900, 'uf' => 'SP', 'descricao' => 'Nova Europa']);
		DB::table('cidades')->insert(['id' => 3533007, 'uf' => 'SP', 'descricao' => 'Nova Granada']);
		DB::table('cidades')->insert(['id' => 3533106, 'uf' => 'SP', 'descricao' => 'Nova Guataporanga']);
		DB::table('cidades')->insert(['id' => 3533205, 'uf' => 'SP', 'descricao' => 'Nova Independência']);
		DB::table('cidades')->insert(['id' => 3533254, 'uf' => 'SP', 'descricao' => 'Novais']);
		DB::table('cidades')->insert(['id' => 3533304, 'uf' => 'SP', 'descricao' => 'Nova Luzitânia']);
		DB::table('cidades')->insert(['id' => 3533403, 'uf' => 'SP', 'descricao' => 'Nova Odessa']);
		DB::table('cidades')->insert(['id' => 3533502, 'uf' => 'SP', 'descricao' => 'Novo Horizonte']);
		DB::table('cidades')->insert(['id' => 3533601, 'uf' => 'SP', 'descricao' => 'Nuporanga']);
		DB::table('cidades')->insert(['id' => 3533700, 'uf' => 'SP', 'descricao' => 'Ocauçu']);
		DB::table('cidades')->insert(['id' => 3533809, 'uf' => 'SP', 'descricao' => 'Óleo']);
		DB::table('cidades')->insert(['id' => 3533908, 'uf' => 'SP', 'descricao' => 'Olímpia']);
		DB::table('cidades')->insert(['id' => 3534005, 'uf' => 'SP', 'descricao' => 'Onda Verde']);
		DB::table('cidades')->insert(['id' => 3534104, 'uf' => 'SP', 'descricao' => 'Oriente']);
		DB::table('cidades')->insert(['id' => 3534203, 'uf' => 'SP', 'descricao' => 'Orindiúva']);
		DB::table('cidades')->insert(['id' => 3534302, 'uf' => 'SP', 'descricao' => 'Orlândia']);
		DB::table('cidades')->insert(['id' => 3534401, 'uf' => 'SP', 'descricao' => 'Osasco']);
		DB::table('cidades')->insert(['id' => 3534500, 'uf' => 'SP', 'descricao' => 'Oscar Bressane']);
		DB::table('cidades')->insert(['id' => 3534609, 'uf' => 'SP', 'descricao' => 'Osvaldo Cruz']);
		DB::table('cidades')->insert(['id' => 3534708, 'uf' => 'SP', 'descricao' => 'Ourinhos']);
		DB::table('cidades')->insert(['id' => 3534757, 'uf' => 'SP', 'descricao' => 'Ouroeste']);
		DB::table('cidades')->insert(['id' => 3534807, 'uf' => 'SP', 'descricao' => 'Ouro Verde']);
		DB::table('cidades')->insert(['id' => 3534906, 'uf' => 'SP', 'descricao' => 'Pacaembu']);
		DB::table('cidades')->insert(['id' => 3535002, 'uf' => 'SP', 'descricao' => 'Palestina']);
		DB::table('cidades')->insert(['id' => 3535101, 'uf' => 'SP', 'descricao' => 'Palmares Paulista']);
		DB::table('cidades')->insert(['id' => 3535200, 'uf' => 'SP', 'descricao' => 'Palmeira d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3535309, 'uf' => 'SP', 'descricao' => 'Palmital']);
		DB::table('cidades')->insert(['id' => 3535408, 'uf' => 'SP', 'descricao' => 'Panorama']);
		DB::table('cidades')->insert(['id' => 3535507, 'uf' => 'SP', 'descricao' => 'Paraguaçu Paulista']);
		DB::table('cidades')->insert(['id' => 3535606, 'uf' => 'SP', 'descricao' => 'Paraibuna']);
		DB::table('cidades')->insert(['id' => 3535705, 'uf' => 'SP', 'descricao' => 'Paraíso']);
		DB::table('cidades')->insert(['id' => 3535804, 'uf' => 'SP', 'descricao' => 'Paranapanema']);
		DB::table('cidades')->insert(['id' => 3535903, 'uf' => 'SP', 'descricao' => 'Paranapuã']);
		DB::table('cidades')->insert(['id' => 3536000, 'uf' => 'SP', 'descricao' => 'Parapuã']);
		DB::table('cidades')->insert(['id' => 3536109, 'uf' => 'SP', 'descricao' => 'Pardinho']);
		DB::table('cidades')->insert(['id' => 3536208, 'uf' => 'SP', 'descricao' => 'Pariquera-Açu']);
		DB::table('cidades')->insert(['id' => 3536257, 'uf' => 'SP', 'descricao' => 'Parisi']);
		DB::table('cidades')->insert(['id' => 3536307, 'uf' => 'SP', 'descricao' => 'Patrocínio Paulista']);
		DB::table('cidades')->insert(['id' => 3536406, 'uf' => 'SP', 'descricao' => 'Paulicéia']);
		DB::table('cidades')->insert(['id' => 3536505, 'uf' => 'SP', 'descricao' => 'Paulínia']);
		DB::table('cidades')->insert(['id' => 3536570, 'uf' => 'SP', 'descricao' => 'Paulistânia']);
		DB::table('cidades')->insert(['id' => 3536604, 'uf' => 'SP', 'descricao' => 'Paulo de Faria']);
		DB::table('cidades')->insert(['id' => 3536703, 'uf' => 'SP', 'descricao' => 'Pederneiras']);
		DB::table('cidades')->insert(['id' => 3536802, 'uf' => 'SP', 'descricao' => 'Pedra Bela']);
		DB::table('cidades')->insert(['id' => 3536901, 'uf' => 'SP', 'descricao' => 'Pedranópolis']);
		DB::table('cidades')->insert(['id' => 3537008, 'uf' => 'SP', 'descricao' => 'Pedregulho']);
		DB::table('cidades')->insert(['id' => 3537107, 'uf' => 'SP', 'descricao' => 'Pedreira']);
		DB::table('cidades')->insert(['id' => 3537156, 'uf' => 'SP', 'descricao' => 'Pedrinhas Paulista']);
		DB::table('cidades')->insert(['id' => 3537206, 'uf' => 'SP', 'descricao' => 'Pedro de Toledo']);
		DB::table('cidades')->insert(['id' => 3537305, 'uf' => 'SP', 'descricao' => 'Penápolis']);
		DB::table('cidades')->insert(['id' => 3537404, 'uf' => 'SP', 'descricao' => 'Pereira Barreto']);
		DB::table('cidades')->insert(['id' => 3537503, 'uf' => 'SP', 'descricao' => 'Pereiras']);
		DB::table('cidades')->insert(['id' => 3537602, 'uf' => 'SP', 'descricao' => 'Peruíbe']);
		DB::table('cidades')->insert(['id' => 3537701, 'uf' => 'SP', 'descricao' => 'Piacatu']);
		DB::table('cidades')->insert(['id' => 3537800, 'uf' => 'SP', 'descricao' => 'Piedade']);
		DB::table('cidades')->insert(['id' => 3537909, 'uf' => 'SP', 'descricao' => 'Pilar do Sul']);
		DB::table('cidades')->insert(['id' => 3538006, 'uf' => 'SP', 'descricao' => 'Pindamonhangaba']);
		DB::table('cidades')->insert(['id' => 3538105, 'uf' => 'SP', 'descricao' => 'Pindorama']);
		DB::table('cidades')->insert(['id' => 3538204, 'uf' => 'SP', 'descricao' => 'Pinhalzinho']);
		DB::table('cidades')->insert(['id' => 3538303, 'uf' => 'SP', 'descricao' => 'Piquerobi']);
		DB::table('cidades')->insert(['id' => 3538501, 'uf' => 'SP', 'descricao' => 'Piquete']);
		DB::table('cidades')->insert(['id' => 3538600, 'uf' => 'SP', 'descricao' => 'Piracaia']);
		DB::table('cidades')->insert(['id' => 3538709, 'uf' => 'SP', 'descricao' => 'Piracicaba']);
		DB::table('cidades')->insert(['id' => 3538808, 'uf' => 'SP', 'descricao' => 'Piraju']);
		DB::table('cidades')->insert(['id' => 3538907, 'uf' => 'SP', 'descricao' => 'Pirajuí']);
		DB::table('cidades')->insert(['id' => 3539004, 'uf' => 'SP', 'descricao' => 'Pirangi']);
		DB::table('cidades')->insert(['id' => 3539103, 'uf' => 'SP', 'descricao' => 'Pirapora do Bom Jesus']);
		DB::table('cidades')->insert(['id' => 3539202, 'uf' => 'SP', 'descricao' => 'Pirapozinho']);
		DB::table('cidades')->insert(['id' => 3539301, 'uf' => 'SP', 'descricao' => 'Pirassununga']);
		DB::table('cidades')->insert(['id' => 3539400, 'uf' => 'SP', 'descricao' => 'Piratininga']);
		DB::table('cidades')->insert(['id' => 3539509, 'uf' => 'SP', 'descricao' => 'Pitangueiras']);
		DB::table('cidades')->insert(['id' => 3539608, 'uf' => 'SP', 'descricao' => 'Planalto']);
		DB::table('cidades')->insert(['id' => 3539707, 'uf' => 'SP', 'descricao' => 'Platina']);
		DB::table('cidades')->insert(['id' => 3539806, 'uf' => 'SP', 'descricao' => 'Poá']);
		DB::table('cidades')->insert(['id' => 3539905, 'uf' => 'SP', 'descricao' => 'Poloni']);
		DB::table('cidades')->insert(['id' => 3540002, 'uf' => 'SP', 'descricao' => 'Pompéia']);
		DB::table('cidades')->insert(['id' => 3540101, 'uf' => 'SP', 'descricao' => 'Pongaí']);
		DB::table('cidades')->insert(['id' => 3540200, 'uf' => 'SP', 'descricao' => 'Pontal']);
		DB::table('cidades')->insert(['id' => 3540259, 'uf' => 'SP', 'descricao' => 'Pontalinda']);
		DB::table('cidades')->insert(['id' => 3540309, 'uf' => 'SP', 'descricao' => 'Pontes Gestal']);
		DB::table('cidades')->insert(['id' => 3540408, 'uf' => 'SP', 'descricao' => 'Populina']);
		DB::table('cidades')->insert(['id' => 3540507, 'uf' => 'SP', 'descricao' => 'Porangaba']);
		DB::table('cidades')->insert(['id' => 3540606, 'uf' => 'SP', 'descricao' => 'Porto Feliz']);
		DB::table('cidades')->insert(['id' => 3540705, 'uf' => 'SP', 'descricao' => 'Porto Ferreira']);
		DB::table('cidades')->insert(['id' => 3540754, 'uf' => 'SP', 'descricao' => 'Potim']);
		DB::table('cidades')->insert(['id' => 3540804, 'uf' => 'SP', 'descricao' => 'Potirendaba']);
		DB::table('cidades')->insert(['id' => 3540853, 'uf' => 'SP', 'descricao' => 'Pracinha']);
		DB::table('cidades')->insert(['id' => 3540903, 'uf' => 'SP', 'descricao' => 'Pradópolis']);
		DB::table('cidades')->insert(['id' => 3541000, 'uf' => 'SP', 'descricao' => 'Praia Grande']);
		DB::table('cidades')->insert(['id' => 3541059, 'uf' => 'SP', 'descricao' => 'Pratânia']);
		DB::table('cidades')->insert(['id' => 3541109, 'uf' => 'SP', 'descricao' => 'Presidente Alves']);
		DB::table('cidades')->insert(['id' => 3541208, 'uf' => 'SP', 'descricao' => 'Presidente Bernardes']);
		DB::table('cidades')->insert(['id' => 3541307, 'uf' => 'SP', 'descricao' => 'Presidente Epitácio']);
		DB::table('cidades')->insert(['id' => 3541406, 'uf' => 'SP', 'descricao' => 'Presidente Prudente']);
		DB::table('cidades')->insert(['id' => 3541505, 'uf' => 'SP', 'descricao' => 'Presidente Venceslau']);
		DB::table('cidades')->insert(['id' => 3541604, 'uf' => 'SP', 'descricao' => 'Promissão']);
		DB::table('cidades')->insert(['id' => 3541653, 'uf' => 'SP', 'descricao' => 'Quadra']);
		DB::table('cidades')->insert(['id' => 3541703, 'uf' => 'SP', 'descricao' => 'Quatá']);
		DB::table('cidades')->insert(['id' => 3541802, 'uf' => 'SP', 'descricao' => 'Queiroz']);
		DB::table('cidades')->insert(['id' => 3541901, 'uf' => 'SP', 'descricao' => 'Queluz']);
		DB::table('cidades')->insert(['id' => 3542008, 'uf' => 'SP', 'descricao' => 'Quintana']);
		DB::table('cidades')->insert(['id' => 3542107, 'uf' => 'SP', 'descricao' => 'Rafard']);
		DB::table('cidades')->insert(['id' => 3542206, 'uf' => 'SP', 'descricao' => 'Rancharia']);
		DB::table('cidades')->insert(['id' => 3542305, 'uf' => 'SP', 'descricao' => 'Redenção da Serra']);
		DB::table('cidades')->insert(['id' => 3542404, 'uf' => 'SP', 'descricao' => 'Regente Feijó']);
		DB::table('cidades')->insert(['id' => 3542503, 'uf' => 'SP', 'descricao' => 'Reginópolis']);
		DB::table('cidades')->insert(['id' => 3542602, 'uf' => 'SP', 'descricao' => 'Registro']);
		DB::table('cidades')->insert(['id' => 3542701, 'uf' => 'SP', 'descricao' => 'Restinga']);
		DB::table('cidades')->insert(['id' => 3542800, 'uf' => 'SP', 'descricao' => 'Ribeira']);
		DB::table('cidades')->insert(['id' => 3542909, 'uf' => 'SP', 'descricao' => 'Ribeirão Bonito']);
		DB::table('cidades')->insert(['id' => 3543006, 'uf' => 'SP', 'descricao' => 'Ribeirão Branco']);
		DB::table('cidades')->insert(['id' => 3543105, 'uf' => 'SP', 'descricao' => 'Ribeirão Corrente']);
		DB::table('cidades')->insert(['id' => 3543204, 'uf' => 'SP', 'descricao' => 'Ribeirão do Sul']);
		DB::table('cidades')->insert(['id' => 3543238, 'uf' => 'SP', 'descricao' => 'Ribeirão dos Índios']);
		DB::table('cidades')->insert(['id' => 3543253, 'uf' => 'SP', 'descricao' => 'Ribeirão Grande']);
		DB::table('cidades')->insert(['id' => 3543303, 'uf' => 'SP', 'descricao' => 'Ribeirão Pires']);
		DB::table('cidades')->insert(['id' => 3543402, 'uf' => 'SP', 'descricao' => 'Ribeirão Preto']);
		DB::table('cidades')->insert(['id' => 3543501, 'uf' => 'SP', 'descricao' => 'Riversul']);
		DB::table('cidades')->insert(['id' => 3543600, 'uf' => 'SP', 'descricao' => 'Rifaina']);
		DB::table('cidades')->insert(['id' => 3543709, 'uf' => 'SP', 'descricao' => 'Rincão']);
		DB::table('cidades')->insert(['id' => 3543808, 'uf' => 'SP', 'descricao' => 'Rinópolis']);
		DB::table('cidades')->insert(['id' => 3543907, 'uf' => 'SP', 'descricao' => 'Rio Claro']);
		DB::table('cidades')->insert(['id' => 3544004, 'uf' => 'SP', 'descricao' => 'Rio das Pedras']);
		DB::table('cidades')->insert(['id' => 3544103, 'uf' => 'SP', 'descricao' => 'Rio Grande da Serra']);
		DB::table('cidades')->insert(['id' => 3544202, 'uf' => 'SP', 'descricao' => 'Riolândia']);
		DB::table('cidades')->insert(['id' => 3544251, 'uf' => 'SP', 'descricao' => 'Rosana']);
		DB::table('cidades')->insert(['id' => 3544301, 'uf' => 'SP', 'descricao' => 'Roseira']);
		DB::table('cidades')->insert(['id' => 3544400, 'uf' => 'SP', 'descricao' => 'Rubiácea']);
		DB::table('cidades')->insert(['id' => 3544509, 'uf' => 'SP', 'descricao' => 'Rubinéia']);
		DB::table('cidades')->insert(['id' => 3544608, 'uf' => 'SP', 'descricao' => 'Sabino']);
		DB::table('cidades')->insert(['id' => 3544707, 'uf' => 'SP', 'descricao' => 'Sagres']);
		DB::table('cidades')->insert(['id' => 3544806, 'uf' => 'SP', 'descricao' => 'Sales']);
		DB::table('cidades')->insert(['id' => 3544905, 'uf' => 'SP', 'descricao' => 'Sales Oliveira']);
		DB::table('cidades')->insert(['id' => 3545001, 'uf' => 'SP', 'descricao' => 'Salesópolis']);
		DB::table('cidades')->insert(['id' => 3545100, 'uf' => 'SP', 'descricao' => 'Salmourão']);
		DB::table('cidades')->insert(['id' => 3545159, 'uf' => 'SP', 'descricao' => 'Saltinho']);
		DB::table('cidades')->insert(['id' => 3545209, 'uf' => 'SP', 'descricao' => 'Salto']);
		DB::table('cidades')->insert(['id' => 3545308, 'uf' => 'SP', 'descricao' => 'Salto de Pirapora']);
		DB::table('cidades')->insert(['id' => 3545407, 'uf' => 'SP', 'descricao' => 'Salto Grande']);
		DB::table('cidades')->insert(['id' => 3545506, 'uf' => 'SP', 'descricao' => 'Sandovalina']);
		DB::table('cidades')->insert(['id' => 3545605, 'uf' => 'SP', 'descricao' => 'Santa Adélia']);
		DB::table('cidades')->insert(['id' => 3545704, 'uf' => 'SP', 'descricao' => 'Santa Albertina']);
		DB::table('cidades')->insert(['id' => 3545803, 'uf' => 'SP', 'descricao' => 'Santa Bárbara d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3546009, 'uf' => 'SP', 'descricao' => 'Santa Branca']);
		DB::table('cidades')->insert(['id' => 3546108, 'uf' => 'SP', 'descricao' => 'Santa Clara d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3546207, 'uf' => 'SP', 'descricao' => 'Santa Cruz da Conceição']);
		DB::table('cidades')->insert(['id' => 3546256, 'uf' => 'SP', 'descricao' => 'Santa Cruz da Esperança']);
		DB::table('cidades')->insert(['id' => 3546306, 'uf' => 'SP', 'descricao' => 'Santa Cruz das Palmeiras']);
		DB::table('cidades')->insert(['id' => 3546405, 'uf' => 'SP', 'descricao' => 'Santa Cruz do Rio Pardo']);
		DB::table('cidades')->insert(['id' => 3546504, 'uf' => 'SP', 'descricao' => 'Santa Ernestina']);
		DB::table('cidades')->insert(['id' => 3546603, 'uf' => 'SP', 'descricao' => 'Santa Fé do Sul']);
		DB::table('cidades')->insert(['id' => 3546702, 'uf' => 'SP', 'descricao' => 'Santa Gertrudes']);
		DB::table('cidades')->insert(['id' => 3546801, 'uf' => 'SP', 'descricao' => 'Santa Isabel']);
		DB::table('cidades')->insert(['id' => 3546900, 'uf' => 'SP', 'descricao' => 'Santa Lúcia']);
		DB::table('cidades')->insert(['id' => 3547007, 'uf' => 'SP', 'descricao' => 'Santa Maria da Serra']);
		DB::table('cidades')->insert(['id' => 3547106, 'uf' => 'SP', 'descricao' => 'Santa Mercedes']);
		DB::table('cidades')->insert(['id' => 3547205, 'uf' => 'SP', 'descricao' => 'Santana da Ponte Pensa']);
		DB::table('cidades')->insert(['id' => 3547304, 'uf' => 'SP', 'descricao' => 'Santana de Parnaíba']);
		DB::table('cidades')->insert(['id' => 3547403, 'uf' => 'SP', 'descricao' => 'Santa Rita d\'Oeste']);
		DB::table('cidades')->insert(['id' => 3547502, 'uf' => 'SP', 'descricao' => 'Santa Rita do Passa Quatro']);
		DB::table('cidades')->insert(['id' => 3547601, 'uf' => 'SP', 'descricao' => 'Santa Rosa de Viterbo']);
		DB::table('cidades')->insert(['id' => 3547650, 'uf' => 'SP', 'descricao' => 'Santa Salete']);
		DB::table('cidades')->insert(['id' => 3547700, 'uf' => 'SP', 'descricao' => 'Santo Anastácio']);
		DB::table('cidades')->insert(['id' => 3547809, 'uf' => 'SP', 'descricao' => 'Santo André']);
		DB::table('cidades')->insert(['id' => 3547908, 'uf' => 'SP', 'descricao' => 'Santo Antônio da Alegria']);
		DB::table('cidades')->insert(['id' => 3548005, 'uf' => 'SP', 'descricao' => 'Santo Antônio de Posse']);
		DB::table('cidades')->insert(['id' => 3548054, 'uf' => 'SP', 'descricao' => 'Santo Antônio do Aracanguá']);
		DB::table('cidades')->insert(['id' => 3548104, 'uf' => 'SP', 'descricao' => 'Santo Antônio do Jardim']);
		DB::table('cidades')->insert(['id' => 3548203, 'uf' => 'SP', 'descricao' => 'Santo Antônio do Pinhal']);
		DB::table('cidades')->insert(['id' => 3548302, 'uf' => 'SP', 'descricao' => 'Santo Expedito']);
		DB::table('cidades')->insert(['id' => 3548401, 'uf' => 'SP', 'descricao' => 'Santópolis do Aguapeí']);
		DB::table('cidades')->insert(['id' => 3548500, 'uf' => 'SP', 'descricao' => 'Santos']);
		DB::table('cidades')->insert(['id' => 3548609, 'uf' => 'SP', 'descricao' => 'São Bento do Sapucaí']);
		DB::table('cidades')->insert(['id' => 3548708, 'uf' => 'SP', 'descricao' => 'São Bernardo do Campo']);
		DB::table('cidades')->insert(['id' => 3548807, 'uf' => 'SP', 'descricao' => 'São Caetano do Sul']);
		DB::table('cidades')->insert(['id' => 3548906, 'uf' => 'SP', 'descricao' => 'São Carlos']);
		DB::table('cidades')->insert(['id' => 3549003, 'uf' => 'SP', 'descricao' => 'São Francisco']);
		DB::table('cidades')->insert(['id' => 3549102, 'uf' => 'SP', 'descricao' => 'São João da Boa Vista']);
		DB::table('cidades')->insert(['id' => 3549201, 'uf' => 'SP', 'descricao' => 'São João das Duas Pontes']);
		DB::table('cidades')->insert(['id' => 3549250, 'uf' => 'SP', 'descricao' => 'São João de Iracema']);
		DB::table('cidades')->insert(['id' => 3549300, 'uf' => 'SP', 'descricao' => 'São João do Pau d\'Alho']);
		DB::table('cidades')->insert(['id' => 3549409, 'uf' => 'SP', 'descricao' => 'São Joaquim da Barra']);
		DB::table('cidades')->insert(['id' => 3549508, 'uf' => 'SP', 'descricao' => 'São José da Bela Vista']);
		DB::table('cidades')->insert(['id' => 3549607, 'uf' => 'SP', 'descricao' => 'São José do Barreiro']);
		DB::table('cidades')->insert(['id' => 3549706, 'uf' => 'SP', 'descricao' => 'São José do Rio Pardo']);
		DB::table('cidades')->insert(['id' => 3549805, 'uf' => 'SP', 'descricao' => 'São José do Rio Preto']);
		DB::table('cidades')->insert(['id' => 3549904, 'uf' => 'SP', 'descricao' => 'São José dos Campos']);
		DB::table('cidades')->insert(['id' => 3549953, 'uf' => 'SP', 'descricao' => 'São Lourenço da Serra']);
		DB::table('cidades')->insert(['id' => 3550001, 'uf' => 'SP', 'descricao' => 'São Luís do Paraitinga']);
		DB::table('cidades')->insert(['id' => 3550100, 'uf' => 'SP', 'descricao' => 'São Manuel']);
		DB::table('cidades')->insert(['id' => 3550209, 'uf' => 'SP', 'descricao' => 'São Miguel Arcanjo']);
		DB::table('cidades')->insert(['id' => 3550308, 'uf' => 'SP', 'descricao' => 'São Paulo']);
		DB::table('cidades')->insert(['id' => 3550407, 'uf' => 'SP', 'descricao' => 'São Pedro']);
		DB::table('cidades')->insert(['id' => 3550506, 'uf' => 'SP', 'descricao' => 'São Pedro do Turvo']);
		DB::table('cidades')->insert(['id' => 3550605, 'uf' => 'SP', 'descricao' => 'São Roque']);
		DB::table('cidades')->insert(['id' => 3550704, 'uf' => 'SP', 'descricao' => 'São Sebastião']);
		DB::table('cidades')->insert(['id' => 3550803, 'uf' => 'SP', 'descricao' => 'São Sebastião da Grama']);
		DB::table('cidades')->insert(['id' => 3550902, 'uf' => 'SP', 'descricao' => 'São Simão']);
		DB::table('cidades')->insert(['id' => 3551009, 'uf' => 'SP', 'descricao' => 'São Vicente']);
		DB::table('cidades')->insert(['id' => 3551108, 'uf' => 'SP', 'descricao' => 'Sarapuí']);
		DB::table('cidades')->insert(['id' => 3551207, 'uf' => 'SP', 'descricao' => 'Sarutaiá']);
		DB::table('cidades')->insert(['id' => 3551306, 'uf' => 'SP', 'descricao' => 'Sebastianópolis do Sul']);
		DB::table('cidades')->insert(['id' => 3551405, 'uf' => 'SP', 'descricao' => 'Serra Azul']);
		DB::table('cidades')->insert(['id' => 3551504, 'uf' => 'SP', 'descricao' => 'Serrana']);
		DB::table('cidades')->insert(['id' => 3551603, 'uf' => 'SP', 'descricao' => 'Serra Negra']);
		DB::table('cidades')->insert(['id' => 3551702, 'uf' => 'SP', 'descricao' => 'Sertãozinho']);
		DB::table('cidades')->insert(['id' => 3551801, 'uf' => 'SP', 'descricao' => 'Sete Barras']);
		DB::table('cidades')->insert(['id' => 3551900, 'uf' => 'SP', 'descricao' => 'Severínia']);
		DB::table('cidades')->insert(['id' => 3552007, 'uf' => 'SP', 'descricao' => 'Silveiras']);
		DB::table('cidades')->insert(['id' => 3552106, 'uf' => 'SP', 'descricao' => 'Socorro']);
		DB::table('cidades')->insert(['id' => 3552205, 'uf' => 'SP', 'descricao' => 'Sorocaba']);
		DB::table('cidades')->insert(['id' => 3552304, 'uf' => 'SP', 'descricao' => 'Sud Mennucci']);
		DB::table('cidades')->insert(['id' => 3552403, 'uf' => 'SP', 'descricao' => 'Sumaré']);
		DB::table('cidades')->insert(['id' => 3552502, 'uf' => 'SP', 'descricao' => 'Suzano']);
		DB::table('cidades')->insert(['id' => 3552551, 'uf' => 'SP', 'descricao' => 'Suzanápolis']);
		DB::table('cidades')->insert(['id' => 3552601, 'uf' => 'SP', 'descricao' => 'Tabapuã']);
		DB::table('cidades')->insert(['id' => 3552700, 'uf' => 'SP', 'descricao' => 'Tabatinga']);
		DB::table('cidades')->insert(['id' => 3552809, 'uf' => 'SP', 'descricao' => 'Taboão da Serra']);
		DB::table('cidades')->insert(['id' => 3552908, 'uf' => 'SP', 'descricao' => 'Taciba']);
		DB::table('cidades')->insert(['id' => 3553005, 'uf' => 'SP', 'descricao' => 'Taguaí']);
		DB::table('cidades')->insert(['id' => 3553104, 'uf' => 'SP', 'descricao' => 'Taiaçu']);
		DB::table('cidades')->insert(['id' => 3553203, 'uf' => 'SP', 'descricao' => 'Taiúva']);
		DB::table('cidades')->insert(['id' => 3553302, 'uf' => 'SP', 'descricao' => 'Tambaú']);
		DB::table('cidades')->insert(['id' => 3553401, 'uf' => 'SP', 'descricao' => 'Tanabi']);
		DB::table('cidades')->insert(['id' => 3553500, 'uf' => 'SP', 'descricao' => 'Tapiraí']);
		DB::table('cidades')->insert(['id' => 3553609, 'uf' => 'SP', 'descricao' => 'Tapiratiba']);
		DB::table('cidades')->insert(['id' => 3553658, 'uf' => 'SP', 'descricao' => 'Taquaral']);
		DB::table('cidades')->insert(['id' => 3553708, 'uf' => 'SP', 'descricao' => 'Taquaritinga']);
		DB::table('cidades')->insert(['id' => 3553807, 'uf' => 'SP', 'descricao' => 'Taquarituba']);
		DB::table('cidades')->insert(['id' => 3553856, 'uf' => 'SP', 'descricao' => 'Taquarivaí']);
		DB::table('cidades')->insert(['id' => 3553906, 'uf' => 'SP', 'descricao' => 'Tarabai']);
		DB::table('cidades')->insert(['id' => 3553955, 'uf' => 'SP', 'descricao' => 'Tarumã']);
		DB::table('cidades')->insert(['id' => 3554003, 'uf' => 'SP', 'descricao' => 'Tatuí']);
		DB::table('cidades')->insert(['id' => 3554102, 'uf' => 'SP', 'descricao' => 'Taubaté']);
		DB::table('cidades')->insert(['id' => 3554201, 'uf' => 'SP', 'descricao' => 'Tejupá']);
		DB::table('cidades')->insert(['id' => 3554300, 'uf' => 'SP', 'descricao' => 'Teodoro Sampaio']);
		DB::table('cidades')->insert(['id' => 3554409, 'uf' => 'SP', 'descricao' => 'Terra Roxa']);
		DB::table('cidades')->insert(['id' => 3554508, 'uf' => 'SP', 'descricao' => 'Tietê']);
		DB::table('cidades')->insert(['id' => 3554607, 'uf' => 'SP', 'descricao' => 'Timburi']);
		DB::table('cidades')->insert(['id' => 3554656, 'uf' => 'SP', 'descricao' => 'Torre de Pedra']);
		DB::table('cidades')->insert(['id' => 3554706, 'uf' => 'SP', 'descricao' => 'Torrinha']);
		DB::table('cidades')->insert(['id' => 3554755, 'uf' => 'SP', 'descricao' => 'Trabiju']);
		DB::table('cidades')->insert(['id' => 3554805, 'uf' => 'SP', 'descricao' => 'Tremembé']);
		DB::table('cidades')->insert(['id' => 3554904, 'uf' => 'SP', 'descricao' => 'Três Fronteiras']);
		DB::table('cidades')->insert(['id' => 3554953, 'uf' => 'SP', 'descricao' => 'Tuiuti']);
		DB::table('cidades')->insert(['id' => 3555000, 'uf' => 'SP', 'descricao' => 'Tupã']);
		DB::table('cidades')->insert(['id' => 3555109, 'uf' => 'SP', 'descricao' => 'Tupi Paulista']);
		DB::table('cidades')->insert(['id' => 3555208, 'uf' => 'SP', 'descricao' => 'Turiúba']);
		DB::table('cidades')->insert(['id' => 3555307, 'uf' => 'SP', 'descricao' => 'Turmalina']);
		DB::table('cidades')->insert(['id' => 3555356, 'uf' => 'SP', 'descricao' => 'Ubarana']);
		DB::table('cidades')->insert(['id' => 3555406, 'uf' => 'SP', 'descricao' => 'Ubatuba']);
		DB::table('cidades')->insert(['id' => 3555505, 'uf' => 'SP', 'descricao' => 'Ubirajara']);
		DB::table('cidades')->insert(['id' => 3555604, 'uf' => 'SP', 'descricao' => 'Uchoa']);
		DB::table('cidades')->insert(['id' => 3555703, 'uf' => 'SP', 'descricao' => 'União Paulista']);
		DB::table('cidades')->insert(['id' => 3555802, 'uf' => 'SP', 'descricao' => 'Urânia']);
		DB::table('cidades')->insert(['id' => 3555901, 'uf' => 'SP', 'descricao' => 'Uru']);
		DB::table('cidades')->insert(['id' => 3556008, 'uf' => 'SP', 'descricao' => 'Urupês']);
		DB::table('cidades')->insert(['id' => 3556107, 'uf' => 'SP', 'descricao' => 'Valentim Gentil']);
		DB::table('cidades')->insert(['id' => 3556206, 'uf' => 'SP', 'descricao' => 'Valinhos']);
		DB::table('cidades')->insert(['id' => 3556305, 'uf' => 'SP', 'descricao' => 'Valparaíso']);
		DB::table('cidades')->insert(['id' => 3556354, 'uf' => 'SP', 'descricao' => 'Vargem']);
		DB::table('cidades')->insert(['id' => 3556404, 'uf' => 'SP', 'descricao' => 'Vargem Grande do Sul']);
		DB::table('cidades')->insert(['id' => 3556453, 'uf' => 'SP', 'descricao' => 'Vargem Grande Paulista']);
		DB::table('cidades')->insert(['id' => 3556503, 'uf' => 'SP', 'descricao' => 'Várzea Paulista']);
		DB::table('cidades')->insert(['id' => 3556602, 'uf' => 'SP', 'descricao' => 'Vera Cruz']);
		DB::table('cidades')->insert(['id' => 3556701, 'uf' => 'SP', 'descricao' => 'Vinhedo']);
		DB::table('cidades')->insert(['id' => 3556800, 'uf' => 'SP', 'descricao' => 'Viradouro']);
		DB::table('cidades')->insert(['id' => 3556909, 'uf' => 'SP', 'descricao' => 'Vista Alegre do Alto']);
		DB::table('cidades')->insert(['id' => 3556958, 'uf' => 'SP', 'descricao' => 'Vitória Brasil']);
		DB::table('cidades')->insert(['id' => 3557006, 'uf' => 'SP', 'descricao' => 'Votorantim']);
		DB::table('cidades')->insert(['id' => 3557105, 'uf' => 'SP', 'descricao' => 'Votuporanga']);
		DB::table('cidades')->insert(['id' => 3557154, 'uf' => 'SP', 'descricao' => 'Zacarias']);
		DB::table('cidades')->insert(['id' => 3557204, 'uf' => 'SP', 'descricao' => 'Chavantes']);
		DB::table('cidades')->insert(['id' => 3557303, 'uf' => 'SP', 'descricao' => 'Estiva Gerbi']);
    }
}
