<?php

use Illuminate\Database\Seeder;

class CidadesTablePRSeeder extends Seeder
{
    /**
     * Alimenta um schema de cidades com as cidades do Paraná
     * @author Cesar André (https://github.com/cesar-andre)
     * @return void
     */
    public function run()
    {
    	DB::table('cidades')->insert(['id' => 4100103, 'uf' => 'PR','descricao' =>  'Abatiá']);
		DB::table('cidades')->insert(['id' => 4100202, 'uf' => 'PR','descricao' =>  'Adrianópolis']);
		DB::table('cidades')->insert(['id' => 4100301, 'uf' => 'PR','descricao' =>  'Agudos do Sul']);
		DB::table('cidades')->insert(['id' => 4100400, 'uf' => 'PR','descricao' =>  'Almirante Tamandaré']);
		DB::table('cidades')->insert(['id' => 4100459, 'uf' => 'PR','descricao' =>  'Altamira do Paraná']);
		DB::table('cidades')->insert(['id' => 4100509, 'uf' => 'PR','descricao' =>  'Altônia']);
		DB::table('cidades')->insert(['id' => 4100608, 'uf' => 'PR','descricao' =>  'Alto Paraná']);
		DB::table('cidades')->insert(['id' => 4100707, 'uf' => 'PR','descricao' =>  'Alto Piquiri']);
		DB::table('cidades')->insert(['id' => 4100806, 'uf' => 'PR','descricao' =>  'Alvorada do Sul']);
		DB::table('cidades')->insert(['id' => 4100905, 'uf' => 'PR','descricao' =>  'Amaporã']);
		DB::table('cidades')->insert(['id' => 4101002, 'uf' => 'PR','descricao' =>  'Ampére']);
		DB::table('cidades')->insert(['id' => 4101051, 'uf' => 'PR','descricao' =>  'Anahy']);
		DB::table('cidades')->insert(['id' => 4101101, 'uf' => 'PR','descricao' =>  'Andirá']);
		DB::table('cidades')->insert(['id' => 4101150, 'uf' => 'PR','descricao' =>  'Ângulo']);
		DB::table('cidades')->insert(['id' => 4101200, 'uf' => 'PR','descricao' =>  'Antonina']);
		DB::table('cidades')->insert(['id' => 4101309, 'uf' => 'PR','descricao' =>  'Antônio Olinto']);
		DB::table('cidades')->insert(['id' => 4101408, 'uf' => 'PR','descricao' =>  'Apucarana']);
		DB::table('cidades')->insert(['id' => 4101507, 'uf' => 'PR','descricao' =>  'Arapongas']);
		DB::table('cidades')->insert(['id' => 4101606, 'uf' => 'PR','descricao' =>  'Arapoti']);
		DB::table('cidades')->insert(['id' => 4101655, 'uf' => 'PR','descricao' =>  'Arapuã']);
		DB::table('cidades')->insert(['id' => 4101705, 'uf' => 'PR','descricao' =>  'Araruna']);
		DB::table('cidades')->insert(['id' => 4101804, 'uf' => 'PR','descricao' =>  'Araucária']);
		DB::table('cidades')->insert(['id' => 4101853, 'uf' => 'PR','descricao' =>  'Ariranha do Ivaí']);
		DB::table('cidades')->insert(['id' => 4101903, 'uf' => 'PR','descricao' =>  'Assaí']);
		DB::table('cidades')->insert(['id' => 4102000, 'uf' => 'PR','descricao' =>  'Assis Chateaubriand']);
		DB::table('cidades')->insert(['id' => 4102109, 'uf' => 'PR','descricao' =>  'Astorga']);
		DB::table('cidades')->insert(['id' => 4102208, 'uf' => 'PR','descricao' =>  'Atalaia']);
		DB::table('cidades')->insert(['id' => 4102307, 'uf' => 'PR','descricao' =>  'Balsa Nova']);
		DB::table('cidades')->insert(['id' => 4102406, 'uf' => 'PR','descricao' =>  'Bandeirantes']);
		DB::table('cidades')->insert(['id' => 4102505, 'uf' => 'PR','descricao' =>  'Barbosa Ferraz']);
		DB::table('cidades')->insert(['id' => 4102604, 'uf' => 'PR','descricao' =>  'Barracão']);
		DB::table('cidades')->insert(['id' => 4102703, 'uf' => 'PR','descricao' =>  'Barra do Jacaré']);
		DB::table('cidades')->insert(['id' => 4102752, 'uf' => 'PR','descricao' =>  'Bela Vista da Caroba']);
		DB::table('cidades')->insert(['id' => 4102802, 'uf' => 'PR','descricao' =>  'Bela Vista do Paraíso']);
		DB::table('cidades')->insert(['id' => 4102901, 'uf' => 'PR','descricao' =>  'Bituruna']);
		DB::table('cidades')->insert(['id' => 4103008, 'uf' => 'PR','descricao' =>  'Boa Esperança']);
		DB::table('cidades')->insert(['id' => 4103024, 'uf' => 'PR','descricao' =>  'Boa Esperança do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4103040, 'uf' => 'PR','descricao' =>  'Boa Ventura de São Roque']);
		DB::table('cidades')->insert(['id' => 4103057, 'uf' => 'PR','descricao' =>  'Boa Vista da Aparecida']);
		DB::table('cidades')->insert(['id' => 4103107, 'uf' => 'PR','descricao' =>  'Bocaiúva do Sul']);
		DB::table('cidades')->insert(['id' => 4103156, 'uf' => 'PR','descricao' =>  'Bom Jesus do Sul']);
		DB::table('cidades')->insert(['id' => 4103206, 'uf' => 'PR','descricao' =>  'Bom Sucesso']);
		DB::table('cidades')->insert(['id' => 4103222, 'uf' => 'PR','descricao' =>  'Bom Sucesso do Sul']);
		DB::table('cidades')->insert(['id' => 4103305, 'uf' => 'PR','descricao' =>  'Borrazópolis']);
		DB::table('cidades')->insert(['id' => 4103354, 'uf' => 'PR','descricao' =>  'Braganey']);
		DB::table('cidades')->insert(['id' => 4103370, 'uf' => 'PR','descricao' =>  'Brasilândia do Sul']);
		DB::table('cidades')->insert(['id' => 4103404, 'uf' => 'PR','descricao' =>  'Cafeara']);
		DB::table('cidades')->insert(['id' => 4103453, 'uf' => 'PR','descricao' =>  'Cafelândia']);
		DB::table('cidades')->insert(['id' => 4103479, 'uf' => 'PR','descricao' =>  'Cafezal do Sul']);
		DB::table('cidades')->insert(['id' => 4103503, 'uf' => 'PR','descricao' =>  'Califórnia']);
		DB::table('cidades')->insert(['id' => 4103602, 'uf' => 'PR','descricao' =>  'Cambará']);
		DB::table('cidades')->insert(['id' => 4103701, 'uf' => 'PR','descricao' =>  'Cambé']);
		DB::table('cidades')->insert(['id' => 4103800, 'uf' => 'PR','descricao' =>  'Cambira']);
		DB::table('cidades')->insert(['id' => 4103909, 'uf' => 'PR','descricao' =>  'Campina da Lagoa']);
		DB::table('cidades')->insert(['id' => 4103958, 'uf' => 'PR','descricao' =>  'Campina do Simão']);
		DB::table('cidades')->insert(['id' => 4104006, 'uf' => 'PR','descricao' =>  'Campina Grande do Sul']);
		DB::table('cidades')->insert(['id' => 4104055, 'uf' => 'PR','descricao' =>  'Campo Bonito']);
		DB::table('cidades')->insert(['id' => 4104105, 'uf' => 'PR','descricao' =>  'Campo do Tenente']);
		DB::table('cidades')->insert(['id' => 4104204, 'uf' => 'PR','descricao' =>  'Campo Largo']);
		DB::table('cidades')->insert(['id' => 4104253, 'uf' => 'PR','descricao' =>  'Campo Magro']);
		DB::table('cidades')->insert(['id' => 4104303, 'uf' => 'PR','descricao' =>  'Campo Mourão']);
		DB::table('cidades')->insert(['id' => 4104402, 'uf' => 'PR','descricao' =>  'Cândido de Abreu']);
		DB::table('cidades')->insert(['id' => 4104428, 'uf' => 'PR','descricao' =>  'Candói']);
		DB::table('cidades')->insert(['id' => 4104451, 'uf' => 'PR','descricao' =>  'Cantagalo']);
		DB::table('cidades')->insert(['id' => 4104501, 'uf' => 'PR','descricao' =>  'Capanema']);
		DB::table('cidades')->insert(['id' => 4104600, 'uf' => 'PR','descricao' =>  'Capitão Leônidas Marques']);
		DB::table('cidades')->insert(['id' => 4104659, 'uf' => 'PR','descricao' =>  'Carambeí']);
		DB::table('cidades')->insert(['id' => 4104709, 'uf' => 'PR','descricao' =>  'Carlópolis']);
		DB::table('cidades')->insert(['id' => 4104808, 'uf' => 'PR','descricao' =>  'Cascavel']);
		DB::table('cidades')->insert(['id' => 4104907, 'uf' => 'PR','descricao' =>  'Castro']);
		DB::table('cidades')->insert(['id' => 4105003, 'uf' => 'PR','descricao' =>  'Catanduvas']);
		DB::table('cidades')->insert(['id' => 4105102, 'uf' => 'PR','descricao' =>  'Centenário do Sul']);
		DB::table('cidades')->insert(['id' => 4105201, 'uf' => 'PR','descricao' =>  'Cerro Azul']);
		DB::table('cidades')->insert(['id' => 4105300, 'uf' => 'PR','descricao' =>  'Céu Azul']);
		DB::table('cidades')->insert(['id' => 4105409, 'uf' => 'PR','descricao' =>  'Chopinzinho']);
		DB::table('cidades')->insert(['id' => 4105508, 'uf' => 'PR','descricao' =>  'Cianorte']);
		DB::table('cidades')->insert(['id' => 4105607, 'uf' => 'PR','descricao' =>  'Cidade Gaúcha']);
		DB::table('cidades')->insert(['id' => 4105706, 'uf' => 'PR','descricao' =>  'Clevelândia']);
		DB::table('cidades')->insert(['id' => 4105805, 'uf' => 'PR','descricao' =>  'Colombo']);
		DB::table('cidades')->insert(['id' => 4105904, 'uf' => 'PR','descricao' =>  'Colorado']);
		DB::table('cidades')->insert(['id' => 4106001, 'uf' => 'PR','descricao' =>  'Congonhinhas']);
		DB::table('cidades')->insert(['id' => 4106100, 'uf' => 'PR','descricao' =>  'Conselheiro Mairinck']);
		DB::table('cidades')->insert(['id' => 4106209, 'uf' => 'PR','descricao' =>  'Contenda']);
		DB::table('cidades')->insert(['id' => 4106308, 'uf' => 'PR','descricao' =>  'Corbélia']);
		DB::table('cidades')->insert(['id' => 4106407, 'uf' => 'PR','descricao' =>  'Cornélio Procópio']);
		DB::table('cidades')->insert(['id' => 4106456, 'uf' => 'PR','descricao' =>  'Coronel Domingos Soares']);
		DB::table('cidades')->insert(['id' => 4106506, 'uf' => 'PR','descricao' =>  'Coronel Vivida']);
		DB::table('cidades')->insert(['id' => 4106555, 'uf' => 'PR','descricao' =>  'Corumbataí do Sul']);
		DB::table('cidades')->insert(['id' => 4106571, 'uf' => 'PR','descricao' =>  'Cruzeiro do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4106605, 'uf' => 'PR','descricao' =>  'Cruzeiro do Oeste']);
		DB::table('cidades')->insert(['id' => 4106704, 'uf' => 'PR','descricao' =>  'Cruzeiro do Sul']);
		DB::table('cidades')->insert(['id' => 4106803, 'uf' => 'PR','descricao' =>  'Cruz Machado']);
		DB::table('cidades')->insert(['id' => 4106852, 'uf' => 'PR','descricao' =>  'Cruzmaltina']);
		DB::table('cidades')->insert(['id' => 4106902, 'uf' => 'PR','descricao' =>  'Curitiba']);
		DB::table('cidades')->insert(['id' => 4107009, 'uf' => 'PR','descricao' =>  'Curiúva']);
		DB::table('cidades')->insert(['id' => 4107108, 'uf' => 'PR','descricao' =>  'Diamante do Norte']);
		DB::table('cidades')->insert(['id' => 4107124, 'uf' => 'PR','descricao' =>  'Diamante do Sul']);
		DB::table('cidades')->insert(['id' => 4107157, 'uf' => 'PR','descricao' =>  'Diamante D\'Oeste']);
		DB::table('cidades')->insert(['id' => 4107207, 'uf' => 'PR','descricao' =>  'Dois Vizinhos']);
		DB::table('cidades')->insert(['id' => 4107256, 'uf' => 'PR','descricao' =>  'Douradina']);
		DB::table('cidades')->insert(['id' => 4107306, 'uf' => 'PR','descricao' =>  'Doutor Camargo']);
		DB::table('cidades')->insert(['id' => 4107405, 'uf' => 'PR','descricao' =>  'Enéas Marques']);
		DB::table('cidades')->insert(['id' => 4107504, 'uf' => 'PR','descricao' =>  'Engenheiro Beltrão']);
		DB::table('cidades')->insert(['id' => 4107520, 'uf' => 'PR','descricao' =>  'Esperança Nova']);
		DB::table('cidades')->insert(['id' => 4107538, 'uf' => 'PR','descricao' =>  'Entre Rios do Oeste']);
		DB::table('cidades')->insert(['id' => 4107546, 'uf' => 'PR','descricao' =>  'Espigão Alto do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4107553, 'uf' => 'PR','descricao' =>  'Farol']);
		DB::table('cidades')->insert(['id' => 4107603, 'uf' => 'PR','descricao' =>  'Faxinal']);
		DB::table('cidades')->insert(['id' => 4107652, 'uf' => 'PR','descricao' =>  'Fazenda Rio Grande']);
		DB::table('cidades')->insert(['id' => 4107702, 'uf' => 'PR','descricao' =>  'Fênix']);
		DB::table('cidades')->insert(['id' => 4107736, 'uf' => 'PR','descricao' =>  'Fernandes Pinheiro']);
		DB::table('cidades')->insert(['id' => 4107751, 'uf' => 'PR','descricao' =>  'Figueira']);
		DB::table('cidades')->insert(['id' => 4107801, 'uf' => 'PR','descricao' =>  'Floraí']);
		DB::table('cidades')->insert(['id' => 4107850, 'uf' => 'PR','descricao' =>  'Flor da Serra do Sul']);
		DB::table('cidades')->insert(['id' => 4107900, 'uf' => 'PR','descricao' =>  'Floresta']);
		DB::table('cidades')->insert(['id' => 4108007, 'uf' => 'PR','descricao' =>  'Florestópolis']);
		DB::table('cidades')->insert(['id' => 4108106, 'uf' => 'PR','descricao' =>  'Flórida']);
		DB::table('cidades')->insert(['id' => 4108205, 'uf' => 'PR','descricao' =>  'Formosa do Oeste']);
		DB::table('cidades')->insert(['id' => 4108304, 'uf' => 'PR','descricao' =>  'Foz do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4108320, 'uf' => 'PR','descricao' =>  'Francisco Alves']);
		DB::table('cidades')->insert(['id' => 4108403, 'uf' => 'PR','descricao' =>  'Francisco Beltrão']);
		DB::table('cidades')->insert(['id' => 4108452, 'uf' => 'PR','descricao' =>  'Foz do Jordão']);
		DB::table('cidades')->insert(['id' => 4108502, 'uf' => 'PR','descricao' =>  'General Carneiro']);
		DB::table('cidades')->insert(['id' => 4108551, 'uf' => 'PR','descricao' =>  'Godoy Moreira']);
		DB::table('cidades')->insert(['id' => 4108601, 'uf' => 'PR','descricao' =>  'Goioerê']);
		DB::table('cidades')->insert(['id' => 4108650, 'uf' => 'PR','descricao' =>  'Goioxim']);
		DB::table('cidades')->insert(['id' => 4108700, 'uf' => 'PR','descricao' =>  'Grandes Rios']);
		DB::table('cidades')->insert(['id' => 4108809, 'uf' => 'PR','descricao' =>  'Guaíra']);
		DB::table('cidades')->insert(['id' => 4108908, 'uf' => 'PR','descricao' =>  'Guairaçá']);
		DB::table('cidades')->insert(['id' => 4108957, 'uf' => 'PR','descricao' =>  'Guamiranga']);
		DB::table('cidades')->insert(['id' => 4109005, 'uf' => 'PR','descricao' =>  'Guapirama']);
		DB::table('cidades')->insert(['id' => 4109104, 'uf' => 'PR','descricao' =>  'Guaporema']);
		DB::table('cidades')->insert(['id' => 4109203, 'uf' => 'PR','descricao' =>  'Guaraci']);
		DB::table('cidades')->insert(['id' => 4109302, 'uf' => 'PR','descricao' =>  'Guaraniaçu']);
		DB::table('cidades')->insert(['id' => 4109401, 'uf' => 'PR','descricao' =>  'Guarapuava']);
		DB::table('cidades')->insert(['id' => 4109500, 'uf' => 'PR','descricao' =>  'Guaraqueçaba']);
		DB::table('cidades')->insert(['id' => 4109609, 'uf' => 'PR','descricao' =>  'Guaratuba']);
		DB::table('cidades')->insert(['id' => 4109658, 'uf' => 'PR','descricao' =>  'Honório Serpa']);
		DB::table('cidades')->insert(['id' => 4109708, 'uf' => 'PR','descricao' =>  'Ibaiti']);
		DB::table('cidades')->insert(['id' => 4109757, 'uf' => 'PR','descricao' =>  'Ibema']);
		DB::table('cidades')->insert(['id' => 4109807, 'uf' => 'PR','descricao' =>  'Ibiporã']);
		DB::table('cidades')->insert(['id' => 4109906, 'uf' => 'PR','descricao' =>  'Icaraíma']);
		DB::table('cidades')->insert(['id' => 4110003, 'uf' => 'PR','descricao' =>  'Iguaraçu']);
		DB::table('cidades')->insert(['id' => 4110052, 'uf' => 'PR','descricao' =>  'Iguatu']);
		DB::table('cidades')->insert(['id' => 4110078, 'uf' => 'PR','descricao' =>  'Imbaú']);
		DB::table('cidades')->insert(['id' => 4110102, 'uf' => 'PR','descricao' =>  'Imbituva']);
		DB::table('cidades')->insert(['id' => 4110201, 'uf' => 'PR','descricao' =>  'Inácio Martins']);
		DB::table('cidades')->insert(['id' => 4110300, 'uf' => 'PR','descricao' =>  'Inajá']);
		DB::table('cidades')->insert(['id' => 4110409, 'uf' => 'PR','descricao' =>  'Indianópolis']);
		DB::table('cidades')->insert(['id' => 4110508, 'uf' => 'PR','descricao' =>  'Ipiranga']);
		DB::table('cidades')->insert(['id' => 4110607, 'uf' => 'PR','descricao' =>  'Iporã']);
		DB::table('cidades')->insert(['id' => 4110656, 'uf' => 'PR','descricao' =>  'Iracema do Oeste']);
		DB::table('cidades')->insert(['id' => 4110706, 'uf' => 'PR','descricao' =>  'Irati']);
		DB::table('cidades')->insert(['id' => 4110805, 'uf' => 'PR','descricao' =>  'Iretama']);
		DB::table('cidades')->insert(['id' => 4110904, 'uf' => 'PR','descricao' =>  'Itaguajé']);
		DB::table('cidades')->insert(['id' => 4110953, 'uf' => 'PR','descricao' =>  'Itaipulândia']);
		DB::table('cidades')->insert(['id' => 4111001, 'uf' => 'PR','descricao' =>  'Itambaracá']);
		DB::table('cidades')->insert(['id' => 4111100, 'uf' => 'PR','descricao' =>  'Itambé']);
		DB::table('cidades')->insert(['id' => 4111209, 'uf' => 'PR','descricao' =>  'Itapejara d\'Oeste']);
		DB::table('cidades')->insert(['id' => 4111258, 'uf' => 'PR','descricao' =>  'Itaperuçu']);
		DB::table('cidades')->insert(['id' => 4111308, 'uf' => 'PR','descricao' =>  'Itaúna do Sul']);
		DB::table('cidades')->insert(['id' => 4111407, 'uf' => 'PR','descricao' =>  'Ivaí']);
		DB::table('cidades')->insert(['id' => 4111506, 'uf' => 'PR','descricao' =>  'Ivaiporã']);
		DB::table('cidades')->insert(['id' => 4111555, 'uf' => 'PR','descricao' =>  'Ivaté']);
		DB::table('cidades')->insert(['id' => 4111605, 'uf' => 'PR','descricao' =>  'Ivatuba']);
		DB::table('cidades')->insert(['id' => 4111704, 'uf' => 'PR','descricao' =>  'Jaboti']);
		DB::table('cidades')->insert(['id' => 4111803, 'uf' => 'PR','descricao' =>  'Jacarezinho']);
		DB::table('cidades')->insert(['id' => 4111902, 'uf' => 'PR','descricao' =>  'Jaguapitã']);
		DB::table('cidades')->insert(['id' => 4112009, 'uf' => 'PR','descricao' =>  'Jaguariaíva']);
		DB::table('cidades')->insert(['id' => 4112108, 'uf' => 'PR','descricao' =>  'Jandaia do Sul']);
		DB::table('cidades')->insert(['id' => 4112207, 'uf' => 'PR','descricao' =>  'Janiópolis']);
		DB::table('cidades')->insert(['id' => 4112306, 'uf' => 'PR','descricao' =>  'Japira']);
		DB::table('cidades')->insert(['id' => 4112405, 'uf' => 'PR','descricao' =>  'Japurá']);
		DB::table('cidades')->insert(['id' => 4112504, 'uf' => 'PR','descricao' =>  'Jardim Alegre']);
		DB::table('cidades')->insert(['id' => 4112603, 'uf' => 'PR','descricao' =>  'Jardim Olinda']);
		DB::table('cidades')->insert(['id' => 4112702, 'uf' => 'PR','descricao' =>  'Jataizinho']);
		DB::table('cidades')->insert(['id' => 4112751, 'uf' => 'PR','descricao' =>  'Jesuítas']);
		DB::table('cidades')->insert(['id' => 4112801, 'uf' => 'PR','descricao' =>  'Joaquim Távora']);
		DB::table('cidades')->insert(['id' => 4112900, 'uf' => 'PR','descricao' =>  'Jundiaí do Sul']);
		DB::table('cidades')->insert(['id' => 4112959, 'uf' => 'PR','descricao' =>  'Juranda']);
		DB::table('cidades')->insert(['id' => 4113007, 'uf' => 'PR','descricao' =>  'Jussara']);
		DB::table('cidades')->insert(['id' => 4113106, 'uf' => 'PR','descricao' =>  'Kaloré']);
		DB::table('cidades')->insert(['id' => 4113205, 'uf' => 'PR','descricao' =>  'Lapa']);
		DB::table('cidades')->insert(['id' => 4113254, 'uf' => 'PR','descricao' =>  'Laranjal']);
		DB::table('cidades')->insert(['id' => 4113304, 'uf' => 'PR','descricao' =>  'Laranjeiras do Sul']);
		DB::table('cidades')->insert(['id' => 4113403, 'uf' => 'PR','descricao' =>  'Leópolis']);
		DB::table('cidades')->insert(['id' => 4113429, 'uf' => 'PR','descricao' =>  'Lidianópolis']);
		DB::table('cidades')->insert(['id' => 4113452, 'uf' => 'PR','descricao' =>  'Lindoeste']);
		DB::table('cidades')->insert(['id' => 4113502, 'uf' => 'PR','descricao' =>  'Loanda']);
		DB::table('cidades')->insert(['id' => 4113601, 'uf' => 'PR','descricao' =>  'Lobato']);
		DB::table('cidades')->insert(['id' => 4113700, 'uf' => 'PR','descricao' =>  'Londrina']);
		DB::table('cidades')->insert(['id' => 4113734, 'uf' => 'PR','descricao' =>  'Luiziana']);
		DB::table('cidades')->insert(['id' => 4113759, 'uf' => 'PR','descricao' =>  'Lunardelli']);
		DB::table('cidades')->insert(['id' => 4113809, 'uf' => 'PR','descricao' =>  'Lupionópolis']);
		DB::table('cidades')->insert(['id' => 4113908, 'uf' => 'PR','descricao' =>  'Mallet']);
		DB::table('cidades')->insert(['id' => 4114005, 'uf' => 'PR','descricao' =>  'Mamborê']);
		DB::table('cidades')->insert(['id' => 4114104, 'uf' => 'PR','descricao' =>  'Mandaguaçu']);
		DB::table('cidades')->insert(['id' => 4114203, 'uf' => 'PR','descricao' =>  'Mandaguari']);
		DB::table('cidades')->insert(['id' => 4114302, 'uf' => 'PR','descricao' =>  'Mandirituba']);
		DB::table('cidades')->insert(['id' => 4114351, 'uf' => 'PR','descricao' =>  'Manfrinópolis']);
		DB::table('cidades')->insert(['id' => 4114401, 'uf' => 'PR','descricao' =>  'Mangueirinha']);
		DB::table('cidades')->insert(['id' => 4114500, 'uf' => 'PR','descricao' =>  'Manoel Ribas']);
		DB::table('cidades')->insert(['id' => 4114609, 'uf' => 'PR','descricao' =>  'Marechal Cândido Rondon']);
		DB::table('cidades')->insert(['id' => 4114708, 'uf' => 'PR','descricao' =>  'Maria Helena']);
		DB::table('cidades')->insert(['id' => 4114807, 'uf' => 'PR','descricao' =>  'Marialva']);
		DB::table('cidades')->insert(['id' => 4114906, 'uf' => 'PR','descricao' =>  'Marilândia do Sul']);
		DB::table('cidades')->insert(['id' => 4115002, 'uf' => 'PR','descricao' =>  'Marilena']);
		DB::table('cidades')->insert(['id' => 4115101, 'uf' => 'PR','descricao' =>  'Mariluz']);
		DB::table('cidades')->insert(['id' => 4115200, 'uf' => 'PR','descricao' =>  'Maringá']);
		DB::table('cidades')->insert(['id' => 4115309, 'uf' => 'PR','descricao' =>  'Mariópolis']);
		DB::table('cidades')->insert(['id' => 4115358, 'uf' => 'PR','descricao' =>  'Maripá']);
		DB::table('cidades')->insert(['id' => 4115408, 'uf' => 'PR','descricao' =>  'Marmeleiro']);
		DB::table('cidades')->insert(['id' => 4115457, 'uf' => 'PR','descricao' =>  'Marquinho']);
		DB::table('cidades')->insert(['id' => 4115507, 'uf' => 'PR','descricao' =>  'Marumbi']);
		DB::table('cidades')->insert(['id' => 4115606, 'uf' => 'PR','descricao' =>  'Matelândia']);
		DB::table('cidades')->insert(['id' => 4115705, 'uf' => 'PR','descricao' =>  'Matinhos']);
		DB::table('cidades')->insert(['id' => 4115739, 'uf' => 'PR','descricao' =>  'Mato Rico']);
		DB::table('cidades')->insert(['id' => 4115754, 'uf' => 'PR','descricao' =>  'Mauá da Serra']);
		DB::table('cidades')->insert(['id' => 4115804, 'uf' => 'PR','descricao' =>  'Medianeira']);
		DB::table('cidades')->insert(['id' => 4115853, 'uf' => 'PR','descricao' =>  'Mercedes']);
		DB::table('cidades')->insert(['id' => 4115903, 'uf' => 'PR','descricao' =>  'Mirador']);
		DB::table('cidades')->insert(['id' => 4116000, 'uf' => 'PR','descricao' =>  'Miraselva']);
		DB::table('cidades')->insert(['id' => 4116059, 'uf' => 'PR','descricao' =>  'Missal']);
		DB::table('cidades')->insert(['id' => 4116109, 'uf' => 'PR','descricao' =>  'Moreira Sales']);
		DB::table('cidades')->insert(['id' => 4116208, 'uf' => 'PR','descricao' =>  'Morretes']);
		DB::table('cidades')->insert(['id' => 4116307, 'uf' => 'PR','descricao' =>  'Munhoz de Melo']);
		DB::table('cidades')->insert(['id' => 4116406, 'uf' => 'PR','descricao' =>  'Nossa Senhora das Graças']);
		DB::table('cidades')->insert(['id' => 4116505, 'uf' => 'PR','descricao' =>  'Nova Aliança do Ivaí']);
		DB::table('cidades')->insert(['id' => 4116604, 'uf' => 'PR','descricao' =>  'Nova América da Colina']);
		DB::table('cidades')->insert(['id' => 4116703, 'uf' => 'PR','descricao' =>  'Nova Aurora']);
		DB::table('cidades')->insert(['id' => 4116802, 'uf' => 'PR','descricao' =>  'Nova Cantu']);
		DB::table('cidades')->insert(['id' => 4116901, 'uf' => 'PR','descricao' =>  'Nova Esperança']);
		DB::table('cidades')->insert(['id' => 4116950, 'uf' => 'PR','descricao' =>  'Nova Esperança do Sudoeste']);
		DB::table('cidades')->insert(['id' => 4117008, 'uf' => 'PR','descricao' =>  'Nova Fátima']);
		DB::table('cidades')->insert(['id' => 4117057, 'uf' => 'PR','descricao' =>  'Nova Laranjeiras']);
		DB::table('cidades')->insert(['id' => 4117107, 'uf' => 'PR','descricao' =>  'Nova Londrina']);
		DB::table('cidades')->insert(['id' => 4117206, 'uf' => 'PR','descricao' =>  'Nova Olímpia']);
		DB::table('cidades')->insert(['id' => 4117214, 'uf' => 'PR','descricao' =>  'Nova Santa Bárbara']);
		DB::table('cidades')->insert(['id' => 4117222, 'uf' => 'PR','descricao' =>  'Nova Santa Rosa']);
		DB::table('cidades')->insert(['id' => 4117255, 'uf' => 'PR','descricao' =>  'Nova Prata do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4117271, 'uf' => 'PR','descricao' =>  'Nova Tebas']);
		DB::table('cidades')->insert(['id' => 4117297, 'uf' => 'PR','descricao' =>  'Novo Itacolomi']);
		DB::table('cidades')->insert(['id' => 4117305, 'uf' => 'PR','descricao' =>  'Ortigueira']);
		DB::table('cidades')->insert(['id' => 4117404, 'uf' => 'PR','descricao' =>  'Ourizona']);
		DB::table('cidades')->insert(['id' => 4117453, 'uf' => 'PR','descricao' =>  'Ouro Verde do Oeste']);
		DB::table('cidades')->insert(['id' => 4117503, 'uf' => 'PR','descricao' =>  'Paiçandu']);
		DB::table('cidades')->insert(['id' => 4117602, 'uf' => 'PR','descricao' =>  'Palmas']);
		DB::table('cidades')->insert(['id' => 4117701, 'uf' => 'PR','descricao' =>  'Palmeira']);
		DB::table('cidades')->insert(['id' => 4117800, 'uf' => 'PR','descricao' =>  'Palmital']);
		DB::table('cidades')->insert(['id' => 4117909, 'uf' => 'PR','descricao' =>  'Palotina']);
		DB::table('cidades')->insert(['id' => 4118006, 'uf' => 'PR','descricao' =>  'Paraíso do Norte']);
		DB::table('cidades')->insert(['id' => 4118105, 'uf' => 'PR','descricao' =>  'Paranacity']);
		DB::table('cidades')->insert(['id' => 4118204, 'uf' => 'PR','descricao' =>  'Paranaguá']);
		DB::table('cidades')->insert(['id' => 4118303, 'uf' => 'PR','descricao' =>  'Paranapoema']);
		DB::table('cidades')->insert(['id' => 4118402, 'uf' => 'PR','descricao' =>  'Paranavaí']);
		DB::table('cidades')->insert(['id' => 4118451, 'uf' => 'PR','descricao' =>  'Pato Bragado']);
		DB::table('cidades')->insert(['id' => 4118501, 'uf' => 'PR','descricao' =>  'Pato Branco']);
		DB::table('cidades')->insert(['id' => 4118600, 'uf' => 'PR','descricao' =>  'Paula Freitas']);
		DB::table('cidades')->insert(['id' => 4118709, 'uf' => 'PR','descricao' =>  'Paulo Frontin']);
		DB::table('cidades')->insert(['id' => 4118808, 'uf' => 'PR','descricao' =>  'Peabiru']);
		DB::table('cidades')->insert(['id' => 4118857, 'uf' => 'PR','descricao' =>  'Perobal']);
		DB::table('cidades')->insert(['id' => 4118907, 'uf' => 'PR','descricao' =>  'Pérola']);
		DB::table('cidades')->insert(['id' => 4119004, 'uf' => 'PR','descricao' =>  'Pérola d\'Oeste']);
		DB::table('cidades')->insert(['id' => 4119103, 'uf' => 'PR','descricao' =>  'Piên']);
		DB::table('cidades')->insert(['id' => 4119152, 'uf' => 'PR','descricao' =>  'Pinhais']);
		DB::table('cidades')->insert(['id' => 4119202, 'uf' => 'PR','descricao' =>  'Pinhalão']);
		DB::table('cidades')->insert(['id' => 4119251, 'uf' => 'PR','descricao' =>  'Pinhal de São Bento']);
		DB::table('cidades')->insert(['id' => 4119301, 'uf' => 'PR','descricao' =>  'Pinhão']);
		DB::table('cidades')->insert(['id' => 4119400, 'uf' => 'PR','descricao' =>  'Piraí do Sul']);
		DB::table('cidades')->insert(['id' => 4119509, 'uf' => 'PR','descricao' =>  'Piraquara']);
		DB::table('cidades')->insert(['id' => 4119608, 'uf' => 'PR','descricao' =>  'Pitanga']);
		DB::table('cidades')->insert(['id' => 4119657, 'uf' => 'PR','descricao' =>  'Pitangueiras']);
		DB::table('cidades')->insert(['id' => 4119707, 'uf' => 'PR','descricao' =>  'Planaltina do Paraná']);
		DB::table('cidades')->insert(['id' => 4119806, 'uf' => 'PR','descricao' =>  'Planalto']);
		DB::table('cidades')->insert(['id' => 4119905, 'uf' => 'PR','descricao' =>  'Ponta Grossa']);
		DB::table('cidades')->insert(['id' => 4119954, 'uf' => 'PR','descricao' =>  'Pontal do Paraná']);
		DB::table('cidades')->insert(['id' => 4120002, 'uf' => 'PR','descricao' =>  'Porecatu']);
		DB::table('cidades')->insert(['id' => 4120101, 'uf' => 'PR','descricao' =>  'Porto Amazonas']);
		DB::table('cidades')->insert(['id' => 4120150, 'uf' => 'PR','descricao' =>  'Porto Barreiro']);
		DB::table('cidades')->insert(['id' => 4120200, 'uf' => 'PR','descricao' =>  'Porto Rico']);
		DB::table('cidades')->insert(['id' => 4120309, 'uf' => 'PR','descricao' =>  'Porto Vitória']);
		DB::table('cidades')->insert(['id' => 4120333, 'uf' => 'PR','descricao' =>  'Prado Ferreira']);
		DB::table('cidades')->insert(['id' => 4120358, 'uf' => 'PR','descricao' =>  'Pranchita']);
		DB::table('cidades')->insert(['id' => 4120408, 'uf' => 'PR','descricao' =>  'Presidente Castelo Branco']);
		DB::table('cidades')->insert(['id' => 4120507, 'uf' => 'PR','descricao' =>  'Primeiro de Maio']);
		DB::table('cidades')->insert(['id' => 4120606, 'uf' => 'PR','descricao' =>  'Prudentópolis']);
		DB::table('cidades')->insert(['id' => 4120655, 'uf' => 'PR','descricao' =>  'Quarto Centenário']);
		DB::table('cidades')->insert(['id' => 4120705, 'uf' => 'PR','descricao' =>  'Quatiguá']);
		DB::table('cidades')->insert(['id' => 4120804, 'uf' => 'PR','descricao' =>  'Quatro Barras']);
		DB::table('cidades')->insert(['id' => 4120853, 'uf' => 'PR','descricao' =>  'Quatro Pontes']);
		DB::table('cidades')->insert(['id' => 4120903, 'uf' => 'PR','descricao' =>  'Quedas do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4121000, 'uf' => 'PR','descricao' =>  'Querência do Norte']);
		DB::table('cidades')->insert(['id' => 4121109, 'uf' => 'PR','descricao' =>  'Quinta do Sol']);
		DB::table('cidades')->insert(['id' => 4121208, 'uf' => 'PR','descricao' =>  'Quitandinha']);
		DB::table('cidades')->insert(['id' => 4121257, 'uf' => 'PR','descricao' =>  'Ramilândia']);
		DB::table('cidades')->insert(['id' => 4121307, 'uf' => 'PR','descricao' =>  'Rancho Alegre']);
		DB::table('cidades')->insert(['id' => 4121356, 'uf' => 'PR','descricao' =>  'Rancho Alegre D\'Oeste']);
		DB::table('cidades')->insert(['id' => 4121406, 'uf' => 'PR','descricao' =>  'Realeza']);
		DB::table('cidades')->insert(['id' => 4121505, 'uf' => 'PR','descricao' =>  'Rebouças']);
		DB::table('cidades')->insert(['id' => 4121604, 'uf' => 'PR','descricao' =>  'Renascença']);
		DB::table('cidades')->insert(['id' => 4121703, 'uf' => 'PR','descricao' =>  'Reserva']);
		DB::table('cidades')->insert(['id' => 4121752, 'uf' => 'PR','descricao' =>  'Reserva do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4121802, 'uf' => 'PR','descricao' =>  'Ribeirão Claro']);
		DB::table('cidades')->insert(['id' => 4121901, 'uf' => 'PR','descricao' =>  'Ribeirão do Pinhal']);
		DB::table('cidades')->insert(['id' => 4122008, 'uf' => 'PR','descricao' =>  'Rio Azul']);
		DB::table('cidades')->insert(['id' => 4122107, 'uf' => 'PR','descricao' =>  'Rio Bom']);
		DB::table('cidades')->insert(['id' => 4122156, 'uf' => 'PR','descricao' =>  'Rio Bonito do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4122172, 'uf' => 'PR','descricao' =>  'Rio Branco do Ivaí']);
		DB::table('cidades')->insert(['id' => 4122206, 'uf' => 'PR','descricao' =>  'Rio Branco do Sul']);
		DB::table('cidades')->insert(['id' => 4122305, 'uf' => 'PR','descricao' =>  'Rio Negro']);
		DB::table('cidades')->insert(['id' => 4122404, 'uf' => 'PR','descricao' =>  'Rolândia']);
		DB::table('cidades')->insert(['id' => 4122503, 'uf' => 'PR','descricao' =>  'Roncador']);
		DB::table('cidades')->insert(['id' => 4122602, 'uf' => 'PR','descricao' =>  'Rondon']);
		DB::table('cidades')->insert(['id' => 4122651, 'uf' => 'PR','descricao' =>  'Rosário do Ivaí']);
		DB::table('cidades')->insert(['id' => 4122701, 'uf' => 'PR','descricao' =>  'Sabáudia']);
		DB::table('cidades')->insert(['id' => 4122800, 'uf' => 'PR','descricao' =>  'Salgado Filho']);
		DB::table('cidades')->insert(['id' => 4122909, 'uf' => 'PR','descricao' =>  'Salto do Itararé']);
		DB::table('cidades')->insert(['id' => 4123006, 'uf' => 'PR','descricao' =>  'Salto do Lontra']);
		DB::table('cidades')->insert(['id' => 4123105, 'uf' => 'PR','descricao' =>  'Santa Amélia']);
		DB::table('cidades')->insert(['id' => 4123204, 'uf' => 'PR','descricao' =>  'Santa Cecília do Pavão']);
		DB::table('cidades')->insert(['id' => 4123303, 'uf' => 'PR','descricao' =>  'Santa Cruz de Monte Castelo']);
		DB::table('cidades')->insert(['id' => 4123402, 'uf' => 'PR','descricao' =>  'Santa Fé']);
		DB::table('cidades')->insert(['id' => 4123501, 'uf' => 'PR','descricao' =>  'Santa Helena']);
		DB::table('cidades')->insert(['id' => 4123600, 'uf' => 'PR','descricao' =>  'Santa Inês']);
		DB::table('cidades')->insert(['id' => 4123709, 'uf' => 'PR','descricao' =>  'Santa Isabel do Ivaí']);
		DB::table('cidades')->insert(['id' => 4123808, 'uf' => 'PR','descricao' =>  'Santa Izabel do Oeste']);
		DB::table('cidades')->insert(['id' => 4123824, 'uf' => 'PR','descricao' =>  'Santa Lúcia']);
		DB::table('cidades')->insert(['id' => 4123857, 'uf' => 'PR','descricao' =>  'Santa Maria do Oeste']);
		DB::table('cidades')->insert(['id' => 4123907, 'uf' => 'PR','descricao' =>  'Santa Mariana']);
		DB::table('cidades')->insert(['id' => 4123956, 'uf' => 'PR','descricao' =>  'Santa Mônica']);
		DB::table('cidades')->insert(['id' => 4124004, 'uf' => 'PR','descricao' =>  'Santana do Itararé']);
		DB::table('cidades')->insert(['id' => 4124020, 'uf' => 'PR','descricao' =>  'Santa Tereza do Oeste']);
		DB::table('cidades')->insert(['id' => 4124053, 'uf' => 'PR','descricao' =>  'Santa Terezinha de Itaipu']);
		DB::table('cidades')->insert(['id' => 4124103, 'uf' => 'PR','descricao' =>  'Santo Antônio da Platina']);
		DB::table('cidades')->insert(['id' => 4124202, 'uf' => 'PR','descricao' =>  'Santo Antônio do Caiuá']);
		DB::table('cidades')->insert(['id' => 4124301, 'uf' => 'PR','descricao' =>  'Santo Antônio do Paraíso']);
		DB::table('cidades')->insert(['id' => 4124400, 'uf' => 'PR','descricao' =>  'Santo Antônio do Sudoeste']);
		DB::table('cidades')->insert(['id' => 4124509, 'uf' => 'PR','descricao' =>  'Santo Inácio']);
		DB::table('cidades')->insert(['id' => 4124608, 'uf' => 'PR','descricao' =>  'São Carlos do Ivaí']);
		DB::table('cidades')->insert(['id' => 4124707, 'uf' => 'PR','descricao' =>  'São Jerônimo da Serra']);
		DB::table('cidades')->insert(['id' => 4124806, 'uf' => 'PR','descricao' =>  'São João']);
		DB::table('cidades')->insert(['id' => 4124905, 'uf' => 'PR','descricao' =>  'São João do Caiuá']);
		DB::table('cidades')->insert(['id' => 4125001, 'uf' => 'PR','descricao' =>  'São João do Ivaí']);
		DB::table('cidades')->insert(['id' => 4125100, 'uf' => 'PR','descricao' =>  'São João do Triunfo']);
		DB::table('cidades')->insert(['id' => 4125209, 'uf' => 'PR','descricao' =>  'São Jorge d\'Oeste']);
		DB::table('cidades')->insert(['id' => 4125308, 'uf' => 'PR','descricao' =>  'São Jorge do Ivaí']);
		DB::table('cidades')->insert(['id' => 4125357, 'uf' => 'PR','descricao' =>  'São Jorge do Patrocínio']);
		DB::table('cidades')->insert(['id' => 4125407, 'uf' => 'PR','descricao' =>  'São José da Boa Vista']);
		DB::table('cidades')->insert(['id' => 4125456, 'uf' => 'PR','descricao' =>  'São José das Palmeiras']);
		DB::table('cidades')->insert(['id' => 4125506, 'uf' => 'PR','descricao' =>  'São José dos Pinhais']);
		DB::table('cidades')->insert(['id' => 4125555, 'uf' => 'PR','descricao' =>  'São Manoel do Paraná']);
		DB::table('cidades')->insert(['id' => 4125605, 'uf' => 'PR','descricao' =>  'São Mateus do Sul']);
		DB::table('cidades')->insert(['id' => 4125704, 'uf' => 'PR','descricao' =>  'São Miguel do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4125753, 'uf' => 'PR','descricao' =>  'São Pedro do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4125803, 'uf' => 'PR','descricao' =>  'São Pedro do Ivaí']);
		DB::table('cidades')->insert(['id' => 4125902, 'uf' => 'PR','descricao' =>  'São Pedro do Paraná']);
		DB::table('cidades')->insert(['id' => 4126009, 'uf' => 'PR','descricao' =>  'São Sebastião da Amoreira']);
		DB::table('cidades')->insert(['id' => 4126108, 'uf' => 'PR','descricao' =>  'São Tomé']);
		DB::table('cidades')->insert(['id' => 4126207, 'uf' => 'PR','descricao' =>  'Sapopema']);
		DB::table('cidades')->insert(['id' => 4126256, 'uf' => 'PR','descricao' =>  'Sarandi']);
		DB::table('cidades')->insert(['id' => 4126272, 'uf' => 'PR','descricao' =>  'Saudade do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4126306, 'uf' => 'PR','descricao' =>  'Sengés']);
		DB::table('cidades')->insert(['id' => 4126355, 'uf' => 'PR','descricao' =>  'Serranópolis do Iguaçu']);
		DB::table('cidades')->insert(['id' => 4126405, 'uf' => 'PR','descricao' =>  'Sertaneja']);
		DB::table('cidades')->insert(['id' => 4126504, 'uf' => 'PR','descricao' =>  'Sertanópolis']);
		DB::table('cidades')->insert(['id' => 4126603, 'uf' => 'PR','descricao' =>  'Siqueira Campos']);
		DB::table('cidades')->insert(['id' => 4126652, 'uf' => 'PR','descricao' =>  'Sulina']);
		DB::table('cidades')->insert(['id' => 4126678, 'uf' => 'PR','descricao' =>  'Tamarana']);
		DB::table('cidades')->insert(['id' => 4126702, 'uf' => 'PR','descricao' =>  'Tamboara']);
		DB::table('cidades')->insert(['id' => 4126801, 'uf' => 'PR','descricao' =>  'Tapejara']);
		DB::table('cidades')->insert(['id' => 4126900, 'uf' => 'PR','descricao' =>  'Tapira']);
		DB::table('cidades')->insert(['id' => 4127007, 'uf' => 'PR','descricao' =>  'Teixeira Soares']);
		DB::table('cidades')->insert(['id' => 4127106, 'uf' => 'PR','descricao' =>  'Telêmaco Borba']);
		DB::table('cidades')->insert(['id' => 4127205, 'uf' => 'PR','descricao' =>  'Terra Boa']);
		DB::table('cidades')->insert(['id' => 4127304, 'uf' => 'PR','descricao' =>  'Terra Rica']);
		DB::table('cidades')->insert(['id' => 4127403, 'uf' => 'PR','descricao' =>  'Terra Roxa']);
		DB::table('cidades')->insert(['id' => 4127502, 'uf' => 'PR','descricao' =>  'Tibagi']);
		DB::table('cidades')->insert(['id' => 4127601, 'uf' => 'PR','descricao' =>  'Tijucas do Sul']);
		DB::table('cidades')->insert(['id' => 4127700, 'uf' => 'PR','descricao' =>  'Toledo']);
		DB::table('cidades')->insert(['id' => 4127809, 'uf' => 'PR','descricao' =>  'Tomazina']);
		DB::table('cidades')->insert(['id' => 4127858, 'uf' => 'PR','descricao' =>  'Três Barras do Paraná']);
		DB::table('cidades')->insert(['id' => 4127882, 'uf' => 'PR','descricao' =>  'Tunas do Paraná']);
		DB::table('cidades')->insert(['id' => 4127908, 'uf' => 'PR','descricao' =>  'Tuneiras do Oeste']);
		DB::table('cidades')->insert(['id' => 4127957, 'uf' => 'PR','descricao' =>  'Tupãssi']);
		DB::table('cidades')->insert(['id' => 4127965, 'uf' => 'PR','descricao' =>  'Turvo']);
		DB::table('cidades')->insert(['id' => 4128005, 'uf' => 'PR','descricao' =>  'Ubiratã']);
		DB::table('cidades')->insert(['id' => 4128104, 'uf' => 'PR','descricao' =>  'Umuarama']);
		DB::table('cidades')->insert(['id' => 4128203, 'uf' => 'PR','descricao' =>  'União da Vitória']);
		DB::table('cidades')->insert(['id' => 4128302, 'uf' => 'PR','descricao' =>  'Uniflor']);
		DB::table('cidades')->insert(['id' => 4128401, 'uf' => 'PR','descricao' =>  'Uraí']);
		DB::table('cidades')->insert(['id' => 4128500, 'uf' => 'PR','descricao' =>  'Wenceslau Braz']);
		DB::table('cidades')->insert(['id' => 4128534, 'uf' => 'PR','descricao' =>  'Ventania']);
		DB::table('cidades')->insert(['id' => 4128559, 'uf' => 'PR','descricao' =>  'Vera Cruz do Oeste']);
		DB::table('cidades')->insert(['id' => 4128609, 'uf' => 'PR','descricao' =>  'Verê']);
		DB::table('cidades')->insert(['id' => 4128625, 'uf' => 'PR','descricao' =>  'Alto Paraíso']);
		DB::table('cidades')->insert(['id' => 4128633, 'uf' => 'PR','descricao' =>  'Doutor Ulysses']);
		DB::table('cidades')->insert(['id' => 4128658, 'uf' => 'PR','descricao' =>  'Virmond']);
		DB::table('cidades')->insert(['id' => 4128708, 'uf' => 'PR','descricao' =>  'Vitorino']);
		DB::table('cidades')->insert(['id' => 4128807, 'uf' => 'PR','descricao' =>  'Xambrê']);
    }
}
