<?php

use Illuminate\Database\Seeder;
use App\Creditopiscofins;

class PisCofinsCredTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ////////////////////////////////////////////////////////  Tipo Crédito PIS/Cofins (Tabela 4.3.6) //////////////////////////////////////////////////////////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'1', 'parent_identificador' => '', 'codigo' => '000', 'descricao' => 'Identificador Tabela 4.3.6']);
        $this->checarExistencia(['identificador'=>'2', 'parent_identificador' => '1','codigo' => '101', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Alíquota Básica']);
        $this->checarExistencia(['identificador'=>'3', 'parent_identificador' => '1','codigo' => '102', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Alíquotas Diferenciadas']);
        $this->checarExistencia(['identificador'=>'4', 'parent_identificador' => '1','codigo' => '103', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Alíquota por Unidade de Produto']);
        $this->checarExistencia(['identificador'=>'5', 'parent_identificador' => '1','codigo' => '104', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Estoque de Abertura']);
        $this->checarExistencia(['identificador'=>'6', 'parent_identificador' => '1','codigo' => '105', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Aquisição Embalagens para revenda']);
        $this->checarExistencia(['identificador'=>'7', 'parent_identificador' => '1','codigo' => '106', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Presumido da Agroindústria']);
        $this->checarExistencia(['identificador'=>'8', 'parent_identificador' => '1','codigo' => '108', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Importação']);
        $this->checarExistencia(['identificador'=>'9', 'parent_identificador' => '1','codigo' => '109', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Atividade Imobiliária']);
        $this->checarExistencia(['identificador'=>'10', 'parent_identificador' => '1','codigo' => '199', 'descricao' => 'Crédito vinculado à receita tributada no mercado interno – Outros']);
        $this->checarExistencia(['identificador'=>'11', 'parent_identificador' => '1','codigo' => '201', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Alíquota Básica']);
        $this->checarExistencia(['identificador'=>'12', 'parent_identificador' => '1','codigo' => '202', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Alíquotas Diferenciadas']);
        $this->checarExistencia(['identificador'=>'13', 'parent_identificador' => '1','codigo' => '203', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Alíquota por Unidade de Produto']);
        $this->checarExistencia(['identificador'=>'14', 'parent_identificador' => '1','codigo' => '204', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Estoque de Abertura']);
        $this->checarExistencia(['identificador'=>'15', 'parent_identificador' => '1','codigo' => '205', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Aquisição Embalagens para revenda']);
        $this->checarExistencia(['identificador'=>'16', 'parent_identificador' => '1','codigo' => '206', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Presumido da Agroindústria']);
        $this->checarExistencia(['identificador'=>'17', 'parent_identificador' => '1','codigo' => '207', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Outros Créditos Presumidos']);
        $this->checarExistencia(['identificador'=>'18', 'parent_identificador' => '1','codigo' => '208', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Importação']);
        $this->checarExistencia(['identificador'=>'19', 'parent_identificador' => '1','codigo' => '299', 'descricao' => 'Crédito vinculado à receita não tributada no mercado interno – Outros']);
        $this->checarExistencia(['identificador'=>'20', 'parent_identificador' => '1','codigo' => '301', 'descricao' => 'Crédito vinculado à receita de exportação – Alíquota Básica']);
        $this->checarExistencia(['identificador'=>'21', 'parent_identificador' => '1','codigo' => '302', 'descricao' => 'Crédito vinculado à receita de exportação – Alíquotas Diferenciadas']);
        $this->checarExistencia(['identificador'=>'22', 'parent_identificador' => '1','codigo' => '303', 'descricao' => 'Crédito vinculado à receita de exportação – Alíquota por Unidade de Produto']);
        $this->checarExistencia(['identificador'=>'23', 'parent_identificador' => '1','codigo' => '304', 'descricao' => 'Crédito vinculado à receita de exportação – Estoque de Abertura']);
        $this->checarExistencia(['identificador'=>'24', 'parent_identificador' => '1','codigo' => '305', 'descricao' => 'Crédito vinculado à receita de exportação – Aquisição Embalagens para revenda']);
        $this->checarExistencia(['identificador'=>'25', 'parent_identificador' => '1','codigo' => '306', 'descricao' => 'Crédito vinculado à receita de exportação – Presumido da Agroindústria']);
        $this->checarExistencia(['identificador'=>'26', 'parent_identificador' => '1','codigo' => '307', 'descricao' => 'Crédito vinculado à receita de exportação – Outros Créditos Presumidos']);
        $this->checarExistencia(['identificador'=>'27', 'parent_identificador' => '1','codigo' => '308', 'descricao' => 'Crédito vinculado à receita de exportação – Importação']);
        $this->checarExistencia(['identificador'=>'28', 'parent_identificador' => '1','codigo' => '399', 'descricao' => 'Crédito vinculado à receita de exportação – Outros']);

        ////////////////////////////////////////////////////Tipo Base Cálculo PIS/Cofins (Tabela 4.3.7) //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'1028', 'parent_identificador' => '','codigo' => '00', 'descricao' => 'Identificador da Tabela 4.3.7']);
        $this->checarExistencia(['identificador'=>'1029', 'parent_identificador' => '1028','codigo' => '01', 'descricao' => 'Aquisição de bens para revenda']);
        $this->checarExistencia(['identificador'=>'1029', 'parent_identificador' => '1028','codigo' => '01', 'descricao' => 'Aquisição de bens para revenda']);
        $this->checarExistencia(['identificador'=>'1030', 'parent_identificador' => '1028','codigo' => '02', 'descricao' => 'Aquisição de bens utilizados como insumo']);
        $this->checarExistencia(['identificador'=>'1031', 'parent_identificador' => '1028','codigo' => '03', 'descricao' => 'Aquisição de serviços utilizados como insumo']);
        $this->checarExistencia(['identificador'=>'1032', 'parent_identificador' => '1028','codigo' => '04', 'descricao' => 'Energia elétrica e térmica, inclusive sob a forma de vapor']);
        $this->checarExistencia(['identificador'=>'1033', 'parent_identificador' => '1028','codigo' => '05', 'descricao' => 'Aluguéis de prédios']);
        $this->checarExistencia(['identificador'=>'1034', 'parent_identificador' => '1028','codigo' => '06', 'descricao' => 'Aluguéis de máquinas e equipamentos']);
        $this->checarExistencia(['identificador'=>'1035', 'parent_identificador' => '1028','codigo' => '07', 'descricao' => 'Armazenagem de mercadoria e frete na operação de venda']);
        $this->checarExistencia(['identificador'=>'1035', 'parent_identificador' => '1028','codigo' => '08', 'descricao' => 'Contraprestações de arrendamento mercantil']);
        $this->checarExistencia(['identificador'=>'1036', 'parent_identificador' => '1028','codigo' => '09', 'descricao' => 'Máquinas, equipamentos e outros bens incorporados ao ativo imobilizado (crédito sobre encargos de depreciação).']);
        $this->checarExistencia(['identificador'=>'1037', 'parent_identificador' => '1028','codigo' => '10', 'descricao' => 'Máquinas, equipamentos e outros bens incorporados ao ativo imobilizado (crédito com base no valor de aquisição).']);
        $this->checarExistencia(['identificador'=>'1038', 'parent_identificador' => '1028','codigo' => '11', 'descricao' => 'Amortização e Depreciação de edificações e benfeitorias em imóveis']);
        $this->checarExistencia(['identificador'=>'1039', 'parent_identificador' => '1028','codigo' => '12', 'descricao' => 'Devolução de Vendas Sujeitas à Incidência Não-Cumulativa']);
        $this->checarExistencia(['identificador'=>'1040', 'parent_identificador' => '1028','codigo' => '13', 'descricao' => 'Outras Operações com Direito a Crédito']);
        $this->checarExistencia(['identificador'=>'1041', 'parent_identificador' => '1028','codigo' => '14', 'descricao' => 'Atividade de Transporte de Cargas – Subcontratação']);
        $this->checarExistencia(['identificador'=>'1042', 'parent_identificador' => '1028','codigo' => '15', 'descricao' => 'Atividade Imobiliária – Custo Incorrido de Unidade Imobiliária']);
        $this->checarExistencia(['identificador'=>'1043', 'parent_identificador' => '1028','codigo' => '16', 'descricao' => 'Atividade Imobiliária – Custo Orçado de unidade não concluída']);
        $this->checarExistencia(['identificador'=>'1044', 'parent_identificador' => '1028','codigo' => '17', 'descricao' => 'Atividade de Prestação de Serviços de Limpeza, Conservação e Manutenção – vale-transporte, vale-refeição ou vale-alimentação, fardamento ou uniforme.']);
        $this->checarExistencia(['identificador'=>'1045', 'parent_identificador' => '1028','codigo' => '18', 'descricao' => 'Estoque de abertura de bens']);

        ////////////////////////////////////////////////////////////////////// Natureza Receita PIS/Cofins (Tabela 4.3.10a 4.3.16) ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///////// case 02
        $this->checarExistencia(['identificador'=>'2000','parent_identificador' => '', 'codigo' => '000', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 02']);
        $this->checarExistencia(['identificador'=>'2045', 'parent_identificador' => '2000', 'codigo' => '101', 'descricao' => 'Gasolinas, Exceto Gasolina de Aviação']);
        $this->checarExistencia(['identificador'=>'2046', 'parent_identificador' => '2000', 'codigo' => '102', 'descricao' => 'Óleo Diesel']);
        $this->checarExistencia(['identificador'=>'2047', 'parent_identificador' => '2000', 'codigo' => '103', 'descricao' => 'Gás Liqüefeito de Petróleo – GLP']);
        $this->checarExistencia(['identificador'=>'2048', 'parent_identificador' => '2000', 'codigo' => '104', 'descricao' => 'Querosene de Aviação']);
        $this->checarExistencia(['identificador'=>'2049', 'parent_identificador' => '2000', 'codigo' => '105', 'descricao' => 'Correntes Destinadas à Formulação de Gasolinas']);
        $this->checarExistencia(['identificador'=>'2050', 'parent_identificador' => '2000', 'codigo' => '106', 'descricao' => 'Correntes Destinadas à Formulação de Óleo Diesel']);
        $this->checarExistencia(['identificador'=>'2051', 'parent_identificador' => '2000', 'codigo' => '107', 'descricao' => 'Nafta Petroquímica Destinada à Formulação de Gasolina ou de Óleo Diesel']);
        $this->checarExistencia(['identificador'=>'2052', 'parent_identificador' => '2000', 'codigo' => '108', 'descricao' => 'Nafta Petroquímica Destinada à Formulação Exclusivamente de Óleo Diesel']);
        $this->checarExistencia(['identificador'=>'2053', 'parent_identificador' => '2000', 'codigo' => '109', 'descricao' => 'Biodiesel']);
        $this->checarExistencia(['identificador'=>'2054', 'parent_identificador' => '2000', 'codigo' => '110', 'descricao' => 'Nafta Petroquímica Destinada às Centrais Petroquímicas']);
        $this->checarExistencia(['identificador'=>'2055', 'parent_identificador' => '2000', 'codigo' => '111', 'descricao' => 'Etano, Propano, Butano e Correntes Gasosas de Refinaria - HLR - Hidrocarbonetos Leves de Refino Destinados à Produção de Eteno e Propeno']);
        $this->checarExistencia(['identificador'=>'2056', 'parent_identificador' => '2000', 'codigo' => '112', 'descricao' => 'Álcool, Inclusive para Fins Carburantes – Venda por Produtor ou Importador.']);
        $this->checarExistencia(['identificador'=>'2057', 'parent_identificador' => '2000', 'codigo' => '113', 'descricao' => 'Álcool, Inclusive para Fins Carburantes – Venda por Distribuidor ou Comerciante Não Varejista.']);
        $this->checarExistencia(['identificador'=>'2058', 'parent_identificador' => '2000', 'codigo' => '201', 'descricao' => 'Produtos Farmacêuticos']);
        $this->checarExistencia(['identificador'=>'2059', 'parent_identificador' => '2000', 'codigo' => '202', 'descricao' => 'Produtos de Perfumaria, de Toucador ou de Higiene Pessoal.']);
        $this->checarExistencia(['identificador'=>'2060', 'parent_identificador' => '2000', 'codigo' => '301', 'descricao' => 'Veículos Automotores e Máquinas Agrícolas Autopropulsadas']);
        $this->checarExistencia(['identificador'=>'2061', 'parent_identificador' => '2000', 'codigo' => '302', 'descricao' => 'Autopeças - Vendas para Atacadistas, Varejistas e Consumidores']);
        $this->checarExistencia(['identificador'=>'2062', 'parent_identificador' => '2000', 'codigo' => '303', 'descricao' => 'Autopeças - Vendas para Fabricantes de Veículos e Máquinas e de Autopeças']);
        $this->checarExistencia(['identificador'=>'2063', 'parent_identificador' => '2000', 'codigo' => '304', 'descricao' => 'Pneumáticos (Pneus Novos e Câmaras-de-Ar)']);
        $this->checarExistencia(['identificador'=>'2064', 'parent_identificador' => '2000', 'codigo' => '401', 'descricao' => 'Águas Minerais Artificiais e Águas Gaseificadas Artificiais']);
        $this->checarExistencia(['identificador'=>'2065', 'parent_identificador' => '2000', 'codigo' => '402', 'descricao' => 'Águas Minerais Naturais, Incluídas as Naturalmente Gaseificadas']);
        $this->checarExistencia(['identificador'=>'2066', 'parent_identificador' => '2000', 'codigo' => '403', 'descricao' => 'Refrigerantes']);
        $this->checarExistencia(['identificador'=>'2067', 'parent_identificador' => '2000', 'codigo' => '404', 'descricao' => 'Preparações Compostas, não Alcoólicas, para Elaboração de Bebida Refrigerante']);
        $this->checarExistencia(['identificador'=>'2068', 'parent_identificador' => '2000', 'codigo' => '405', 'descricao' => 'Refrescos, Isotônicos e Energéticos']);
        $this->checarExistencia(['identificador'=>'2069', 'parent_identificador' => '2000', 'codigo' => '406', 'descricao' => 'Cervejas de Malte e Cervejas Sem Álcool']);
        $this->checarExistencia(['identificador'=>'2070', 'parent_identificador' => '2000', 'codigo' => '407', 'descricao' => 'Chope e Cervejas de Malte Quando Vendidas a Granel']);

        /////////////////////////////////////////////////////////case 3///////////////////////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'3000','codigo' => '000', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 03']);
        $this->checarExistencia(['identificador'=>'3071', 'parent_identificador' => '3000','codigo' => '700', 'descricao' => 'EMBALAGENS DE BEBIDAS FRIAS']);
        $this->checarExistencia(['identificador'=>'3072', 'parent_identificador' => '3000','codigo' => '701', 'descricao' => 'Embalagens de Vidro não Retornáveis para Refrigerantes ou Cervejas']);
        $this->checarExistencia(['identificador'=>'3073', 'parent_identificador' => '3000','codigo' => '702', 'descricao' => 'Embalagens de Vidro Retornáveis para Refrigerantes ou Cervejas']);
        $this->checarExistencia(['identificador'=>'3074', 'parent_identificador' => '3000','codigo' => '703', 'descricao' => 'Garrafas e Garrafões com Capacidade Nominal de Envasamento Inferior a 10 Litros']);
        $this->checarExistencia(['identificador'=>'3075', 'parent_identificador' => '3000','codigo' => '704', 'descricao' => 'Garrafas e Garrafões com Capacidade Nominal de Envasamento Igual ou Superior a 10 Litros']);
        $this->checarExistencia(['identificador'=>'3076', 'parent_identificador' => '3000','codigo' => '705', 'descricao' => 'Lata de Aço para Refrigerantes, Cervejas sem Álcool ou Água']);
        $this->checarExistencia(['identificador'=>'3077', 'parent_identificador' => '3000','codigo' => '706', 'descricao' => 'Lata de Aço para Cervejas de Malte']);
        $this->checarExistencia(['identificador'=>'3078', 'parent_identificador' => '3000','codigo' => '707', 'descricao' => 'Lata de Alumínio para Refrigerantes, Cervejas sem Álcool ou Água']);
        $this->checarExistencia(['identificador'=>'3079', 'parent_identificador' => '3000','codigo' => '708', 'descricao' => 'Lata de Alumínio para Cervejas de Malte']);
        $this->checarExistencia(['identificador'=>'3080', 'parent_identificador' => '3000','codigo' => '709', 'descricao' => 'Pré-Formas de Embalagens com Faixa de Gramatura de até 30 g  ']);
        $this->checarExistencia(['identificador'=>'3081', 'parent_identificador' => '3000','codigo' => '710', 'descricao' => 'Pré-Formas de Embalagens com Faixa de Gramatura Acima de 30 até 42 g']);
        $this->checarExistencia(['identificador'=>'3082', 'parent_identificador' => '3000','codigo' => '711', 'descricao' => 'Pré-Formas de Embalagens com Faixa de Gramatura Acima de 42 g']);
        $this->checarExistencia(['identificador'=>'3083', 'parent_identificador' => '3000','codigo' => '800', 'descricao' => 'BEBIDAS FRIAS']);
        $this->checarExistencia(['identificador'=>'3084', 'parent_identificador' => '3000','codigo' => '001', 'descricao' => 'Categoria 41 – REFRI – Água Mineral Artificial']);
        $this->checarExistencia(['identificador'=>'3085', 'parent_identificador' => '3000','codigo' => '811', 'descricao' => 'Águas Minerais Artificiais - Todas as Embalagens ']);
        $this->checarExistencia(['identificador'=>'3086', 'parent_identificador' => '3000','codigo' => '812', 'descricao' => 'Águas Gaseificadas Artificiais - Todas as Embalagens']);
        $this->checarExistencia(['identificador'=>'3087', 'parent_identificador' => '3000','codigo' => '002', 'descricao' => 'Categoria 42 – REFRI – Água Mineral Natural, Incluídas as Naturalmente Gaseificadas']);
        $this->checarExistencia(['identificador'=>'3088', 'parent_identificador' => '3000','codigo' => '821', 'descricao' => 'Águas Minerais Naturais Envasadas em Embalagens de Capacidade até 10 Litros']);
        $this->checarExistencia(['identificador'=>'3089', 'parent_identificador' => '3000','codigo' => '822', 'descricao' => 'Águas Minerais Naturais Envasadas em Embalagens de Capacidade Acima de 10 Litros']);
        $this->checarExistencia(['identificador'=>'3090', 'parent_identificador' => '3000','codigo' => '003', 'descricao' => 'Categoria 43 – REFRI – Águas e Refrigerantes, em PET/Plástico']);
        $this->checarExistencia(['identificador'=>'3091', 'parent_identificador' => '3000','codigo' => '831', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 01']);
        $this->checarExistencia(['identificador'=>'3092', 'parent_identificador' => '3000','codigo' => '832', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 02']);
        $this->checarExistencia(['identificador'=>'3093', 'parent_identificador' => '3000','codigo' => '833', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 03']);
        $this->checarExistencia(['identificador'=>'3094', 'parent_identificador' => '3000','codigo' => '834', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 04']);
        $this->checarExistencia(['identificador'=>'3095', 'parent_identificador' => '3000','codigo' => '835', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 05']);
        $this->checarExistencia(['identificador'=>'3096', 'parent_identificador' => '3000','codigo' => '836', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 06']);
        $this->checarExistencia(['identificador'=>'3097', 'parent_identificador' => '3000','codigo' => '837', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 07']);
        $this->checarExistencia(['identificador'=>'3098', 'parent_identificador' => '3000','codigo' => '838', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 08']);
        $this->checarExistencia(['identificador'=>'3099', 'parent_identificador' => '3000','codigo' => '839', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 09']);
        $this->checarExistencia(['identificador'=>'3100', 'parent_identificador' => '3000','codigo' => '840', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 10']);
        $this->checarExistencia(['identificador'=>'3101', 'parent_identificador' => '3000','codigo' => '841', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 11']);
        $this->checarExistencia(['identificador'=>'3102', 'parent_identificador' => '3000','codigo' => '842', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 12']);
        $this->checarExistencia(['identificador'=>'3103', 'parent_identificador' => '3000','codigo' => '843', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 13']);
        $this->checarExistencia(['identificador'=>'3104', 'parent_identificador' => '3000','codigo' => '844', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 14']);
        $this->checarExistencia(['identificador'=>'3105', 'parent_identificador' => '3000','codigo' => '845', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 15']);
        $this->checarExistencia(['identificador'=>'3106', 'parent_identificador' => '3000','codigo' => '846', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 16']);
        $this->checarExistencia(['identificador'=>'3107', 'parent_identificador' => '3000','codigo' => '847', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 17']);
        $this->checarExistencia(['identificador'=>'3108', 'parent_identificador' => '3000','codigo' => '848', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 18']);
        $this->checarExistencia(['identificador'=>'3109', 'parent_identificador' => '3000','codigo' => '849', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 19']);
        $this->checarExistencia(['identificador'=>'3110', 'parent_identificador' => '3000','codigo' => '850', 'descricao' => 'Águas e Refrigerantes, em PET/Plástico - Grupo 20']);
        $this->checarExistencia(['identificador'=>'3111', 'parent_identificador' => '3000','codigo' => '004', 'descricao' => 'Categoria 44 – REFRI – Águas e Refrigerantes, em Lata']);
        $this->checarExistencia(['identificador'=>'3112', 'parent_identificador' => '3000','codigo' => '861', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 01']);
        $this->checarExistencia(['identificador'=>'3113', 'parent_identificador' => '3000','codigo' => '862', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 02']);
        $this->checarExistencia(['identificador'=>'3114', 'parent_identificador' => '3000','codigo' => '863', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 03']);
        $this->checarExistencia(['identificador'=>'3115', 'parent_identificador' => '3000','codigo' => '864', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 04']);
        $this->checarExistencia(['identificador'=>'3116', 'parent_identificador' => '3000','codigo' => '865', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 05']);
        $this->checarExistencia(['identificador'=>'3117', 'parent_identificador' => '3000','codigo' => '866', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 06']);
        $this->checarExistencia(['identificador'=>'3118', 'parent_identificador' => '3000','codigo' => '867', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 07']);
        $this->checarExistencia(['identificador'=>'3119', 'parent_identificador' => '3000','codigo' => '868', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 10']);
        $this->checarExistencia(['identificador'=>'3120', 'parent_identificador' => '3000','codigo' => '869', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 11']);
        $this->checarExistencia(['identificador'=>'3121', 'parent_identificador' => '3000','codigo' => '870', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 12']);
        $this->checarExistencia(['identificador'=>'3122', 'parent_identificador' => '3000','codigo' => '871', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 13']);
        $this->checarExistencia(['identificador'=>'3123', 'parent_identificador' => '3000','codigo' => '872', 'descricao' => 'Águas e Refrigerantes, em Lata - Grupo 14']);
        $this->checarExistencia(['identificador'=>'3124', 'parent_identificador' => '3000','codigo' => '005', 'descricao' => 'Categoria 45 - REFRI - Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas']);
        $this->checarExistencia(['identificador'=>'3125', 'parent_identificador' => '3000','codigo' => '881', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 01']);
        $this->checarExistencia(['identificador'=>'3126', 'parent_identificador' => '3000','codigo' => '882', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 02']);
        $this->checarExistencia(['identificador'=>'3127', 'parent_identificador' => '3000','codigo' => '883', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 03']);
        $this->checarExistencia(['identificador'=>'3128', 'parent_identificador' => '3000','codigo' => '884', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 04']);
        $this->checarExistencia(['identificador'=>'3129', 'parent_identificador' => '3000','codigo' => '885', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 05']);
        $this->checarExistencia(['identificador'=>'3130', 'parent_identificador' => '3000','codigo' => '886', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 06']);
        $this->checarExistencia(['identificador'=>'3131', 'parent_identificador' => '3000','codigo' => '887', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 07']);
        $this->checarExistencia(['identificador'=>'3132', 'parent_identificador' => '3000','codigo' => '888', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 08']);
        $this->checarExistencia(['identificador'=>'3133', 'parent_identificador' => '3000','codigo' => '889', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 09']);
        $this->checarExistencia(['identificador'=>'3134', 'parent_identificador' => '3000','codigo' => '890', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 10']);
        $this->checarExistencia(['identificador'=>'3135', 'parent_identificador' => '3000','codigo' => '891', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 11']);
        $this->checarExistencia(['identificador'=>'3136', 'parent_identificador' => '3000','codigo' => '892', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 12']);
        $this->checarExistencia(['identificador'=>'3137', 'parent_identificador' => '3000','codigo' => '893', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 13']);
        $this->checarExistencia(['identificador'=>'3138', 'parent_identificador' => '3000','codigo' => '894', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 14']);
        $this->checarExistencia(['identificador'=>'3139', 'parent_identificador' => '3000','codigo' => '895', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 15']);
        $this->checarExistencia(['identificador'=>'3140', 'parent_identificador' => '3000','codigo' => '896', 'descricao' => 'Águas e Refrigerantes, em Vidro e Outras Embalagens Não Especificadas - Grupo 16']);

        ///////////////////////////////////////////2/////////////////////// case 5 ///////////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'4000','parent_identificador' => '', 'codigo' => '000', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 05']);
        $this->checarExistencia(['identificador'=>'4141','parent_identificador' => '4000', 'codigo' => '101', 'descricao' => 'Cigarros, de fumo (tabaco) ou dos seus sucedâneos']);
        $this->checarExistencia(['identificador'=>'4142','parent_identificador' => '4000', 'codigo' => '201', 'descricao' => 'Motocicletas (incluídos os ciclomotores) e outros ciclos equipados com motor auxiliar, mesmo com carro lateral; carros laterais']);
        $this->checarExistencia(['identificador'=>'4143','parent_identificador' => '4000', 'codigo' => '301', 'descricao' => 'Semeadores, plantadores e transplantadores']);
        $this->checarExistencia(['identificador'=>'4144','parent_identificador' => '4000', 'codigo' => '401', 'descricao' => 'Álcool, inclusive para fins carburantes – Vendas por Produtor/Importador']);
        $this->checarExistencia(['identificador'=>'4145','parent_identificador' => '4000', 'codigo' => '402', 'descricao' => 'Álcool, inclusive para fins carburantes – Vendas por Distribuidor']);
        $this->checarExistencia(['identificador'=>'4146','parent_identificador' => '4000', 'codigo' => '403', 'descricao' => 'Gasolinas, Óleo Dieses e GLP']);
        $this->checarExistencia(['identificador'=>'4147','parent_identificador' => '4000', 'codigo' => '404', 'descricao' => 'Veiculos']);
        $this->checarExistencia(['identificador'=>'4148','parent_identificador' => '4000', 'codigo' => '405', 'descricao' => 'Autopeças']);
        $this->checarExistencia(['identificador'=>'4149','parent_identificador' => '4000', 'codigo' => '406', 'descricao' => 'Pneus']);
        $this->checarExistencia(['identificador'=>'4150','parent_identificador' => '4000', 'codigo' => '407', 'descricao' => 'Bebidas Frias']);
        $this->checarExistencia(['identificador'=>'4151','parent_identificador' => '4000', 'codigo' => '408', 'descricao' => 'Embalagens para bebidas Frias']);
        $this->checarExistencia(['identificador'=>'4152','parent_identificador' => '4000', 'codigo' => '409', 'descricao' => 'Artigos de Perfumaria']);

        ///////////////////////////////////////////2//////////////////// case 6 ///////////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'5000','parent_identificador' => '','codigo' => '000', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 06']);
        $this->checarExistencia(['identificador'=>'5153','parent_identificador' => '5000','codigo' => '301', 'descricao' => 'Produtos classificados na posição 87.13 da NCM (cadeiras de rodas e outros veículos)']);
        $this->checarExistencia(['identificador'=>'5154','parent_identificador' => '5000','codigo' => '302', 'descricao' => 'Artigos e aparelhos ortopédicos ou para fraturas classificados no código 90.21.10 da NCM']);
        $this->checarExistencia(['identificador'=>'5155','parent_identificador' => '5000','codigo' => '303', 'descricao' => 'Artigos e aparelhos de próteses classificados no código 90.21.3 da NCM']);
        $this->checarExistencia(['identificador'=>'5156','parent_identificador' => '5000','codigo' => '304', 'descricao' => 'Almofadas antiescaras classificadas nos Capítulos 39, 40, 63 e 94 da NCM']);
        $this->checarExistencia(['identificador'=>'5157','parent_identificador' => '5000','codigo' => '305', 'descricao' => 'Bens relacionados em ato do Poder Executivo para aplicação nas Unidades Modulares de Saúde de que trata o Convênio ICMS no 114/2009 quando vendidos a órgãos da administração pública direta federal, estadual, distrital e municipal']);
        $this->checarExistencia(['identificador'=>'5158','parent_identificador' => '5000','codigo' => '306', 'descricao' => 'Produtos químicosclassificados no Capítulo 29 da Nomenclatura Comum do Mercosul - NCM']);
        $this->checarExistencia(['identificador'=>'5159','parent_identificador' => '5000','codigo' => '307', 'descricao' => 'Produtos químicos intermediários de síntese, classificados no Capítulo 29 da NCM']);
        $this->checarExistencia(['identificador'=>'5160','parent_identificador' => '5000','codigo' => '308', 'descricao' => 'Produtos destinados ao uso em hospitais, clínicas e consultórios médicos e odontológicos, campanhas de saúde realizadas pelo poder público, laboratório de anatomia patológica, citológica ou de análises clínicas, classificados nas posições 30.02, 30.06, 39.26, 40.15 e 90.18, da NCM']);
        $this->checarExistencia(['identificador'=>'5161','parent_identificador' => '5000','codigo' => '401', 'descricao' => 'Venda a varejo de unidades de processamento digital classificadas no código 8471.50.10 da TIPI, desde que o preço de venda de cada unidade não exceda a R$ 2.000,00']);
        $this->checarExistencia(['identificador'=>'5162','parent_identificador' => '5000','codigo' => '402', 'descricao' => 'Venda a varejo de máquinas automáticas para processamento de dados, digitais, portáteis, de peso inferior a 3,5Kg (três quilos e meio), com tela (écran) de área superior a 140cm2 (cento e quarenta centímetros quadrados), classificadas nos códigos 8471.30.12, 8471.30.19 ou 8471.30.90 da TIPI, desde que o preço de venda de cada máquina não exceda a R$ 4.000,00']);
        $this->checarExistencia(['identificador'=>'5163','parent_identificador' => '5000','codigo' => '403', 'descricao' => 'Venda a varejo de máquinas automáticas de processamento de dados, apresentadas sob a forma de sistemas, do código 8471.49 da TIPI, contendo exclusivamente 1 (uma) unidade de processamento digital, 1 (uma) unidade de saída por vídeo (monitor), 1 (um) teclado (unidade de entrada), 1 (um) mouse (unidade de entrada), classificados, respectivamente, nos códigos 8471.50.10, 8471.60.7, 8471.60.52 e 8471.60.53 da TIPI, desde que o preço de venda de cada sistema não exceda a R$ 4.000,00 (dois mil e quinhentos reais)']);
        $this->checarExistencia(['identificador'=>'5164','parent_identificador' => '5000','codigo' => '404', 'descricao' => 'Venda a varejo de teclado (unidade de entrada) e de mouse (unidade de entrada) classificados, respectivamente, nos códigos 8471.60.52 e 8471.60.53 da TIPI, quando acompanharem a unidade de processamento digital classificada no código 8471.50.10 da TIPI, desde que o preço de venda de cada conjunto não exceda a R$ 2.100,00 (dois mil e cem reais).']);
        $this->checarExistencia(['identificador'=>'5165','parent_identificador' => '5000','codigo' => '405', 'descricao' => 'PADIS - Programa de Apoio ao Desenvolvimento Tecnológico da Indústria de Semicondutores']);
        $this->checarExistencia(['identificador'=>'5166','parent_identificador' => '5000','codigo' => '406', 'descricao' => 'PATVD - Programa de Apoio ao Desenvolvimento Tecnológico da Indústria de Equipamentos para a TV Digital']);
        $this->checarExistencia(['identificador'=>'5167','parent_identificador' => '5000','codigo' => '900', 'descricao' => 'DEMAIS PRODUTOS E RECEITAS']);
        $this->checarExistencia(['identificador'=>'5168','parent_identificador' => '5000','codigo' => '901', 'descricao' => 'Papel destinado à impressão de jornais']);
        $this->checarExistencia(['identificador'=>'5169','parent_identificador' => '5000','codigo' => '902', 'descricao' => 'Papéis classificados nos códigos 4801.00.10, 4801.00.90, 4802.61.91, 4802.61.99, 4810.19.89 e 4810.22.90, todos da TIPI, destinados à impressão de periódicos']);
        $this->checarExistencia(['identificador'=>'5170','parent_identificador' => '5000','codigo' => '903', 'descricao' => 'Livros, conforme definido no art. 2o da Lei no 10.753/03']);
        $this->checarExistencia(['identificador'=>'5171','parent_identificador' => '5000','codigo' => '904', 'descricao' => 'Preparações compostas não-alcoólicas, classificadas no código 2106.90.10 Ex 01 da TIPI, destinadas à elaboração de bebidas pelas pessoas jurídicas industriais dos produtos referidos no art. 58-A da Lei no 10.833/2003']);
        $this->checarExistencia(['identificador'=>'5172','parent_identificador' => '5000','codigo' => '905', 'descricao' => 'Material de defesa, classificado nas posições 87.10.00.00 e 89.06.10.00 da TIPI, além de partes, peças, componentes, ferramentais, insumos, equipamentos e matérias-primas a serem empregados na sua industrialização, montagem, manutenção, modernização e conversão']);
        $this->checarExistencia(['identificador'=>'5173','parent_identificador' => '5000','codigo' => '906', 'descricao' => 'Equipamentos de controle de produção, inclusive medidores de vazão, condutivímetros, aparelhos para controle, registro, gravação e transmissão dos quantitativos medidos, quando adquiridos por pessoas jurídicas legalmente obrigadas à sua utilização']);
        $this->checarExistencia(['identificador'=>'5174','parent_identificador' => '5000','codigo' => '907', 'descricao' => 'Valores pagos ou creditados pelos Estados, Distrito Federal e Municípios relativos ao ICMS e ao ISS, no âmbito de programas de concessão de crédito voltados ao estímulo à solicitação de documento fiscal na aquisição de mercadorias e serviços']);
        $this->checarExistencia(['identificador'=>'5175','parent_identificador' => '5000','codigo' => '908', 'descricao' => 'Vendas de mercadorias destinadas ao consumo ou à industrialização na Zona Franca de Manaus – ZFM']);
        $this->checarExistencia(['identificador'=>'5176','parent_identificador' => '5000','codigo' => '909', 'descricao' => 'Vendas de mercadorias destinadas ao consumo ou à industrialização nas Áreas de Livre Comércio – ALC, exceto quando tiver como destinatárias pessoas jurídicas atacadistas e varejistas, sujeitas ao regime de apuração não cumulativa da Contribuição para o PIS/Pasep e da Cofins']);
        $this->checarExistencia(['identificador'=>'5177','parent_identificador' => '5000','codigo' => '910', 'descricao' => 'Vendas de matérias-primas, produtos intermediários e materiais de embalagem, produzidos na Zona Franca de Manaus para emprego em processo de industrialização por estabelecimentos industriais ali instalados e consoante projetos aprovados pelo SUFRAMA']);
        $this->checarExistencia(['identificador'=>'5178','parent_identificador' => '5000','codigo' => '911', 'descricao' => 'Receitas financeiras, inclusive decorrentes de operações realizadas para fins de hedge, auferidas pelas pessoas jurídicas sujeitas ao regime de incidência não-cumulativa']);
        $this->checarExistencia(['identificador'=>'5179','parent_identificador' => '5000','codigo' => '912', 'descricao' => 'Aquisição no mercado interno ou a importação, de forma combinada ou não, de mercadoria equivalente à empregada ou consumida na industrialização de produto exportado (Drawback Reposição de Estoque), inclusive:']);
        $this->checarExistencia(['identificador'=>'5180','parent_identificador' => '5000','codigo' => '999', 'descricao' => 'Outros Produtos e Receitas']);

        ///////////////////////////////////////////2/////////// case 7 //////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'6000','parent_identificador' => '', 'codigo' => '101', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 07']);
        $this->checarExistencia(['identificador'=>'6181','parent_identificador' => '6000', 'codigo' => '101', 'descricao' => 'Fornecimento de mercadorias ou serviços para uso ou consumo de bordo em embarcações e aeronaves em tráfego internacional, quando o pagamento for efetuado em moeda conversível (exceto querosene de aviação)']);
        $this->checarExistencia(['identificador'=>'6182','parent_identificador' => '6000', 'codigo' => '102', 'descricao' => 'Transporte internacional de cargas ou passageiros']);
        $this->checarExistencia(['identificador'=>'6183','parent_identificador' => '6000', 'codigo' => '103', 'descricao' => 'Receitas auferidas pelos estaleiros navais brasileiros nas atividades de construção, conservação, modernização, conversão e reparo de embarcações pré-registradas ou registradas no Registro Especial Brasileiro (REB), instituído pela Lei nº 9.432, de 8 de janeiro de 1997']);
        $this->checarExistencia(['identificador'=>'6184','parent_identificador' => '6000', 'codigo' => '104', 'descricao' => 'Frete de mercadorias transportadas entre o País e o exterior pelas embarcações registradas no REB, de que trata o art. 11 da Lei nº 9.432, de 1997']);
        $this->checarExistencia(['identificador'=>'6185','parent_identificador' => '6000', 'codigo' => '201', 'descricao' => 'Receitas relativas às atividades próprias dos templos de qualquer culto; partidos políticos; instituições de educação e de assistência social que preencham as condições e requisitos do art. 12 da Lei nº 9.532, de 10 de dezembro de 1997; instituições de caráter filantrópico, recreativo, cultural, científico e as associações, que preencham as condições e requisitos do art. 15 da Lei nº 9.532, de 1997; sindicatos, federações e confederações; serviços sociais autônomos, criados ou autorizados por lei; conselhos de fiscalização de profissões regulamentadas; fundações de direito privado; condomínios de proprietários de imóveis residenciais ou comerciais; e Organização das Cooperativas Brasileiras (OCB) e as Organizações Estaduais de Cooperativas previstas no art. 105 e seu § 1º da Lei nº 5.764, de 16 de dezembro de 1971.']);
        $this->checarExistencia(['identificador'=>'6186','parent_identificador' => '6000', 'codigo' => '202', 'descricao' => 'Receitas das entidades beneficentes de assistência social com a finalidade de prestação de serviços nas áreas de assistência social, saúde ou educação, que atendam aos requisitos do art. 29 da Lei nº 12.101, de 27 de novembro de 2009.']);
        $this->checarExistencia(['identificador'=>'6187','parent_identificador' => '6000', 'codigo' => '301', 'descricao' => 'Venda de energia elétrica pela Itaipu Binacional']);
        $this->checarExistencia(['identificador'=>'6188','parent_identificador' => '6000', 'codigo' => '401', 'descricao' => 'Importação de bens ou mercadorias para uso ou consumo exclusivo na organização e realização dos referidos eventos, promovida pela Fifa, Subsidiária Fifa no Brasil, Confederações Fifa, Associações estrangeiras membros da Fifa, Parceiros Comerciais da Fifa domiciliados no exterior, Emissora Fonte da Fifa e Prestadores de Serviço da Fifa domiciliados no exterior, ou por intermédio de pessoa jurídica por eles contratada para representá-los']);
        $this->checarExistencia(['identificador'=>'6189','parent_identificador' => '6000', 'codigo' => '402', 'descricao' => 'Receita auferida por Subsidiária Fifa no Brasil, decorrente das atividades próprias e diretamente vinculadas à organização ou realização dos referidos eventos, exceto as receitas decorrentes da venda de ingressos e de pacotes de hospedagem.']);
        $this->checarExistencia(['identificador'=>'6190','parent_identificador' => '6000', 'codigo' => '403', 'descricao' => 'Receita das atividades próprias, auferida pelos Prestadores de Serviços da FIFA, estabelecidos no País sob a forma de sociedade com finalidade específica para o desenvolvimento de atividades diretamente relacionadas à realização dos eventos.']);
        $this->checarExistencia(['identificador'=>'6191','parent_identificador' => '6000', 'codigo' => '901', 'descricao' => 'Recursos recebidos a título de repasse, oriundos do Orçamento Geral da União, dos Estados, do Distrito Federal e dos Municípios, pelas empresas públicas e sociedades de economia mista']);
        $this->checarExistencia(['identificador'=>'6192','parent_identificador' => '6000', 'codigo' => '902', 'descricao' => 'Receita da instituição privada de ensino superior, com fins lucrativos ou sem fins lucrativos não beneficente, que aderir ao Programa Universidade para Todos (Prouni), no período de vigência do termo de adesão, decorrentes da realização de atividades de ensino superior, proveniente de cursos de graduação ou cursos seqüenciais de formação específica']);
        $this->checarExistencia(['identificador'=>'6193','parent_identificador' => '6000', 'codigo' => '999', 'descricao' => 'Outras receitas com isenção']);

        ///////////////////////////////////////////2////////////////////////// case 8 ////////////////////////////////////
        $this->checarExistencia(['identificador'=>'7000','parent_identificador' => '','codigo' => '000', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 08']);
        $this->checarExistencia(['identificador'=>'7194','parent_identificador' => '7000','codigo' => '101', 'descricao' => 'Venda de querosene de aviação por pessoa jurídica não enquadrada na condição de importadora ou produtora']);
        $this->checarExistencia(['identificador'=>'7195','parent_identificador' => '7000','codigo' => '102', 'descricao' => 'Venda de querosene de aviação por produtora ou importadora a distribuidora, quando o produto for destinado ao consumo por aeronave em tráfego internacional']);
        $this->checarExistencia(['identificador'=>'7196','parent_identificador' => '7000','codigo' => '201', 'descricao' => 'Vendas de biodiesel por pessoas não enquadradas como produtor ou importador']);
        $this->checarExistencia(['identificador'=>'7197','parent_identificador' => '7000','codigo' => '301', 'descricao' => 'Vendas de materiais e equipamentos, bem assim da prestação de serviços decorrentes dessas operações, efetuadas diretamente a Itaipu Binacional']);
        $this->checarExistencia(['identificador'=>'7198','parent_identificador' => '7000','codigo' => '401', 'descricao' => 'Exportação de mercadorias para o exterior']);
        $this->checarExistencia(['identificador'=>'7199','parent_identificador' => '7000','codigo' => '402', 'descricao' => 'Serviços prestados a pessoas físicas ou jurídicas residentes ou domiciliadas no exterior, cujo pagamento represente ingresso de divisas']);
        $this->checarExistencia(['identificador'=>'7200','parent_identificador' => '7000','codigo' => '403', 'descricao' => 'Vendas, com o fim específico de exportação, a empresa comercial exportadora constituída nos termos do Decreto-Lei nº 1.248, de 29 de novembro de 1972, ou simplesmente registrada na Secretaria de Comércio Exterior (Secex) do Ministério do Desenvolvimento, Indústria e Comércio Exterior']);
        $this->checarExistencia(['identificador'=>'7201','parent_identificador' => '7000','codigo' => '901', 'descricao' => 'Regime Cumulativo - Demais receitas não classificadas como faturamento']);
        $this->checarExistencia(['identificador'=>'7202','parent_identificador' => '7000','codigo' => '999', 'descricao' => 'Outras receitas sem incidência']);

        ///////////////////////////////////////////2////////////////////// case 9 //////////////////////////////////////////
        $this->checarExistencia(['identificador'=>'8000','parent_identificador' => '','codigo' => '101', 'descricao' => 'Identificador Tabela 4.3.10 a 4.3.16 caso 09']);
        $this->checarExistencia(['identificador'=>'8203','parent_identificador' => '8000','codigo' => '101', 'descricao' => 'Vendas a pessoa jurídica preponderantemente exportadora']);
        $this->checarExistencia(['identificador'=>'8204','parent_identificador' => '8000','codigo' => '102', 'descricao' => 'Vendas a fabricante de veículos e carros blindados de combate, (NCM 8710.00.00) para uso pelas forças armadas ou órgãos de segurança pública brasileiros.']);
        $this->checarExistencia(['identificador'=>'8205','parent_identificador' => '8000','codigo' => '103', 'descricao' => 'Aquisição no mercado interno ou a importação, de forma combinada ou não, de mercadoria para emprego ou consumo na industrialização de produto a ser exportado, por pessoa jurídica previamente habilitada pela Secretaria de Comércio Exterior (Drawback Integrado)']);
        $this->checarExistencia(['identificador'=>'8206','parent_identificador' => '8000','codigo' => '104', 'descricao' => 'aquisição no mercado interno ou à importação de mercadorias para emprego em reparo, criação, cultivo ou atividade extrativista de produto a ser exportado.']);
        $this->checarExistencia(['identificador'=>'8207','parent_identificador' => '8000','codigo' => '105', 'descricao' => 'Aquisição no mercado interno ou importações de empresas denominadas fabricantes-intermediários, para industrialização de produto intermediário a ser diretamente fornecido a empresas industriais-exportadoras, para emprego ou consumo na industrialização de produto final destinado à exportação (Drawback Intermediário)']);
        $this->checarExistencia(['identificador'=>'8208','parent_identificador' => '8000','codigo' => '201', 'descricao' => 'Insumos de origem animal, utilizados na fabricação de produtos destinados à alimentação humana ou animal, classificados na NCM capítulos 2 (exceto os códigos 02.01, 02.02, 0206.10.00, 0206.20, 0206.21, 0206.29), 3 (exceto os produtos vivos desse capítulo), 4, 8 a 12, 15 (exceto o código 1502.00.1), 16 e 23 e nos códigos 0504.00, 0701.90.00, 0702.00.00, 0706.10.00, 07.08, 0709.90, 07.10, 07.12 a 07.14 (exceto os códigos 0713.33.19, 0713.33.29 e 0713.33.99), 1701.11.00, 1701.99.00, 1702.90.00, 18.01, 18.03, 1804.00.00, 1805.00.00, 20.09, 2101.11.10 e 2209.00.00.']);
        $this->checarExistencia(['identificador'=>'8209','parent_identificador' => '8000','codigo' => '202', 'descricao' => 'Insumos de origem vegetal, utilizados na fabricação de produtos destinados à alimentação humana ou animal, classificados na NCM capítulos 2 (exceto os códigos 02.01, 02.02, 0206.10.00, 0206.20, 0206.21, 0206.29), 3 (exceto os produtos vivos desse capítulo), 4, 8 a 12, 15 (exceto o código 1502.00.1), 16 e 23 e nos códigos 0504.00, 0701.90.00, 0702.00.00, 0706.10.00, 07.08, 0709.90, 07.10, 07.12 a 07.14 (exceto os códigos 0713.33.19, 0713.33.29 e 0713.33.99), 1701.11.00, 1701.99.00, 1702.90.00, 18.01, 18.03, 1804.00.00, 1805.00.00, 20.09, 2101.11.10 e 2209.00.00.']);
        $this->checarExistencia(['identificador'=>'8210','parent_identificador' => '8000','codigo' => '203', 'descricao' => 'Soja e seus derivados classificados nos Capítulos 12, 15 e 23, todos da TIPI']);
        $this->checarExistencia(['identificador'=>'8211','parent_identificador' => '8000','codigo' => '204', 'descricao' => 'Venda de cerealista que exerça cumulativamente as atividades de limpar, padronizar, armazenar e comercializar os produtos in natura de origem vegetal, classificados nos códigos 09.01, 10.01 a 10.08, (exceto os dos códigos 1006.20 e 1006.30, 12.01 e 18.01) da NCM.']);
        $this->checarExistencia(['identificador'=>'8212','parent_identificador' => '8000','codigo' => '205', 'descricao' => 'Venda a granel de leite in natura, efetuada por pessoa jurídica que exerça cumulativamente as atividades de transporte e resfriamento deste produto']);
        $this->checarExistencia(['identificador'=>'8213','parent_identificador' => '8000','codigo' => '206', 'descricao' => 'Venda por PJ que exerça atividade agropecuária ou por cooperativa de produção agropecuária de produto in natura de origem vegetal destinado à elaboração de mercadorias classificadas no código 22.04, da NCM']);
        $this->checarExistencia(['identificador'=>'8214','parent_identificador' => '8000','codigo' => '207', 'descricao' => 'Venda de animais vivos classificados na posição 01.02, à pessoa jurídica que produza mercadoria classificada nas posições 02.01, 02.02, 02.06.10.00, 02.06.20, 02.06.21, 02.06.29, 05.06.90.00, 05.10.00.10 e 15.02.00.1 da NCM']);
        $this->checarExistencia(['identificador'=>'8215','parent_identificador' => '8000','codigo' => '208', 'descricao' => 'Vendas de produtos classificados nas posições 02.01, 02.02, 0206.10.00, 0206.20, 0206.21, 0206.29, 0506.90.00, 0510.00.10 e 1502.00.1, quando efetuadas por pessoa jurídica que industrialize bens e produtos classificados nas posições 01.02, 02.01 e 02.02 da NCM']);
        $this->checarExistencia(['identificador'=>'8216','parent_identificador' => '8000','codigo' => '209', 'descricao' => 'Receita bruta da venda, no mercado interno, de:']);
        $this->checarExistencia(['identificador'=>'8217','parent_identificador' => '8000','codigo' => '301', 'descricao' => 'REPES - Regime Especial de Tributação para a Plataforma de Exportação de Serviços de Tecnologia da Informação.']);
        $this->checarExistencia(['identificador'=>'8218','parent_identificador' => '8000','codigo' => '302', 'descricao' => 'RECAP - Regime Especial de Aquisição de Bens de Capital para Empresas Exportadoras.']);
        $this->checarExistencia(['identificador'=>'8219','parent_identificador' => '8000','codigo' => '303', 'descricao' => 'REIDI - Regime Especial de Incentivos para o Desenvolvimento da Infra-Estrutura.']);
        $this->checarExistencia(['identificador'=>'8220','parent_identificador' => '8000','codigo' => '304', 'descricao' => 'REPENEC - Regime Especial de Incentivos para o Desenvolvimento de Infraestrutura da Indústria Petrolífera nas Regiões Norte, Nordeste e Centro-Oeste.']);
        $this->checarExistencia(['identificador'=>'8221','parent_identificador' => '8000','codigo' => '305', 'descricao' => 'REPORTO - Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária.']);
        $this->checarExistencia(['identificador'=>'8222','parent_identificador' => '8000','codigo' => '306', 'descricao' => 'RECOMPE - Regime Especial de Aquisição de Computadores para Uso Educacional.']);
        $this->checarExistencia(['identificador'=>'8223','parent_identificador' => '8000','codigo' => '307', 'descricao' => 'RETAERO - Regime Especial para a Indústria Aeronáutica Brasileira.']);
        $this->checarExistencia(['identificador'=>'8224','parent_identificador' => '8000','codigo' => '308', 'descricao' => 'RECOPA - Regime Especial de Tributação para Construção, Ampliação, Reforma ou Modernização de Estádios de Futebol.']);
        $this->checarExistencia(['identificador'=>'8225','parent_identificador' => '8000','codigo' => '309', 'descricao' => 'ZFM – Zona Franca de Manaus.']);
        $this->checarExistencia(['identificador'=>'8226','parent_identificador' => '8000','codigo' => '310', 'descricao' => 'ZPE – Zonas de Processamento de Exportação.']);
        $this->checarExistencia(['identificador'=>'8227','parent_identificador' => '8000','codigo' => '311', 'descricao' => 'Vendas realizadas no mercado interno para a Fifa, para Subsidiária Fifa no Brasil ou para a Emissora Fonte da Fifa, de mercadorias destinadas a uso ou consumo exclusivo na organização e realização da Copa das Confederações Fifa 2013 e da Copa do Mundo Fifa 2014.']);
        $this->checarExistencia(['identificador'=>'8228','parent_identificador' => '8000','codigo' => '401', 'descricao' => 'Receitas de Fretes e de transporte multimodal, contratadas por pessoa jurídica preponderantemente exportadora, para transporte no mercado interno de produtos com suspensão ou destinados a Exportação.']);
        $this->checarExistencia(['identificador'=>'8229','parent_identificador' => '8000','codigo' => '402', 'descricao' => 'Venda de cana-de-açúcar, classificada na posição 12.12 da Nomenclatura Comum do Mercosul – NCM, efetuada para pessoa jurídica produtora de álcool, inclusive para fins carburantes, tributada no regime de não cumulatividade.']);
        $this->checarExistencia(['identificador'=>'8230','parent_identificador' => '8000','codigo' => '403', 'descricao' => 'Venda de óleo combustível, tipo bunker, MF - Marine Fuel, classificado no código 2710.19.22, óleo combustível, tipo bunker, MGO - Marine Gás Oil, classificado no código 2710.19.21 e óleo combustível, tipo bunker, ODM - Óleo Diesel Marítimo, classificado no código 2710.19.21, quando destinados à navegação de cabotagem e de apoio portuário e marítimo, para a pessoa jurídica previamente habilitada']);
        $this->checarExistencia(['identificador'=>'8231','parent_identificador' => '8000','codigo' => '404', 'descricao' => 'Acetona classificada no código 2914.11.00 da Tabela de Incidência do Imposto sobre Produtos Industrializados – Tipi, destinada à produção de monoisopropilamina (Mipa) utilizada na elaboração de defensivos agropecuários classificados na posição 38.08 da Tipi']);
        $this->checarExistencia(['identificador'=>'8232','parent_identificador' => '8000','codigo' => '405', 'descricao' => 'Desperdícios, resíduos ou aparas de plástico, de papel ou cartão, de vidro, de ferro ou aço, de cobre, de níquel, de alumínio, de chumbo, de zinco e de estanho, e demais desperdícios e resíduos metálicos do Capítulo 81 da Tipi']);
        $this->checarExistencia(['identificador'=>'8233','parent_identificador' => '8000','codigo' => '406', 'descricao' => 'Venda de produtos à pessoa jurídica sediada no exterior, com contrato de entrega no território nacional, de insumos destinados à industrialização, por conta e ordem da encomendante sediada no exterior, de máquinas e veículos classificados nas posições 87.01 a 87.05 da TIPI']);
        $this->checarExistencia(['identificador'=>'8234','parent_identificador' => '8000','codigo' => '407', 'descricao' => 'Vendas a empresa sediada no exterior, para entrega em território nacional, de material de embalagem a ser totalmente utilizados no acondicionamento de mercadoria destinada à exportação para o exterior']);
        $this->checarExistencia(['identificador'=>'8235','parent_identificador' => '8000','codigo' => '408', 'descricao' => 'Venda de máquinas e equipamentos classificados na posição 84.39, utilizados na fabricação de papéis destinados à impressão de jornais ou de papéis classificados nos códigos 4801.00.10, 4801.00.90, 4802.61.91, 4802.61.99, 4810.19.39 e 4810.22.90, todos da Tipi, destinados à impressão de periódicos, quando os referidos bens forem adquiridos por pessoa jurídica industrial para incorporação ao seu ativo imobilizado']);
        $this->checarExistencia(['identificador'=>'8236','parent_identificador' => '8000','codigo' => '901', 'descricao' => 'Doações em espécie recebidas por instituições financeiras públicas controladas pela União e destinadas a ações de prevenção, monitoramento e combate ao desmatamento, inclusive programas de remuneração por serviços ambientais, e de promoção da conservação e do uso sustentável dos biomas brasileiros, na forma estabelecida pelo Decreto nº 6.565, de 15 de setembro de 2008']);
        $this->checarExistencia(['identificador'=>'8237','parent_identificador' => '8000','codigo' => '999', 'descricao' => 'Outras operações com suspensão']);
    }

    private function checarExistencia($array)
    {
        // FASE 3: count() sobre Model/null gera erro fatal no PHP 7.4+.
        // Usamos checagem de nulidade (equivalente à intenção original).
        $cred = Creditopiscofins::where('identificador', $array["identificador"])->first();
        if (! is_null($cred)) {
            $up = $cred->update($array);
        } else {
            Creditopiscofins::create($array);
        }
    }
}
